### ISSUE TITLE
old docker images

### ISSUE THREAD

**Issue by t5unamie** [osixia/docker-openldap#104]
why are the older docker images being removed. They worked perfectly fine.

**Comment by t5unamie** [comment]
Would really appreciate it if the old docker images like 1.1.2 are restored since they worked for me.

**Comment by osixia** [comment]
Sorry i can't,
v1.1.2 dependencies didn't work anymore and i'm unable to rebuild the image. (cfssl link are dead)
Sorry for the inconveniance but i had too many issues from old image version.

I will keep old images anyway from now thanks.
