### ISSUE TITLE
default server not listening on port 636

### ISSUE THREAD

**Issue by chewmanfoo** [osixia/docker-openldap#11]
Not sure if this is a bug or if I'm just misunderstanding you, or misunderstanding openldap - sorry if this is noise...

I start this container like this:

    $ sudo docker run -d osixia/openldap
    73f55020614de923bce196d5dc02259fabd4f8c88b978db939c129cdb2b9970a

and I see this:

    $ sudo docker ps
    CONTAINER ID IMAGE                  COMMAND         CREATED      STATUS        PORTS                   NAMES
    73f55020614d osixia/openldap:0.10.1 "/sbin/my_init" 3 seconds ago Up 2 seconds 389/tcp      prickly_albattani

Shouldn't it be listening on 636?

**Comment by chewmanfoo** [comment]
Thanks so much for this container!  It's excellent.

**Comment by osixia** [comment]
Hello,
Thanks :)

ldaps support (for legacy clients that can't use StartTLS) will be added in the next release, see : #10 
But consider using start tls if you can, ldaps is deprecated. 

More info :
http://www.openldap.org/faq/data/cache/605.html
http://www.openldap.org/faq/data/cache/185.html

**Comment by osixia** [comment]
fixed in 2f7ea270bf8f548bb5212464c98497a3f9966ce3
