### ISSUE TITLE
Bootstrap volume

### ISSUE THREAD

**Issue by cgarnier** [osixia/docker-openldap#118]
Hello, 
It could be nice to add a bootstrap volume to allow to pre configure the openldap at first startup.

For instance, i would like to be able to put a bunch of ldif files into a volume and expect they are automaticaly imported at first startup. 
Like it s done on mysql docker. (https://hub.docker.com/_/mysql/)

**Comment by osixia** [comment]
Hello,
this is already possible but more complex than with the mysql image:

For example if your ldif files are in `/data/ldif` on your host, mount this directory as a volume to any location in the container for example `/tmp/ldif` and copy them to `/container/service/slapd/assets/config/bootstrap/ldif/`

```
docker run -v /data/ldif:/tmp/ldif osixia/openldap --cmd "cp -a /tmp/ldif/. /container/service/slapd/assets/config/bootstrap/ldif/"
```

Note that you can't mount directly you ldif folder to /container/service/slapd/assets/config/bootstrap/ldif/ without breaking everything.

But let's make it more simple in a next version :)

**Comment by osixia** [comment]
To see all run options of this image:
docker run osixia/openldap --help

**Comment by bersace** [comment]
Hi,

To get this working I need `--copy-service` on the command line and to specify `changetype: add` to each entry. This make `ldapmodify` behave like `ldapadd`

Without this, i got:

```
ldap_1      | + ldapmodify -h localhost -p 389 -D cn=admin,dc=ldap,dc=ldap2pg,dc=docker -w integral -f /container/run/service/slapd/ass
ets/config/bootstrap/ldif/95-data.ldif                                                                                                 
ldap_1      | + log-helper debug                                                                                                       
ldap_1      | 596eee85 conn=1026 fd=16 ACCEPT from IP=127.0.0.1:57444 (IP=127.0.0.1:389)                                               
ldap_1      | 596eee85 conn=1026 op=0 BIND dn="cn=admin,dc=ldap,dc=ldap2pg,dc=docker" method=128                                       
ldap_1      | 596eee85 conn=1026 op=0 BIND dn="cn=admin,dc=ldap,dc=ldap2pg,dc=docker" mech=SIMPLE ssf=0                                
ldap_1      | 596eee85 conn=1026 op=0 RESULT tag=97 err=0 text=                                                                        
ldap_1      | 596eee85 conn=1026 op=1 ADD dn="cn=slap,dc=ldap,dc=ldap2pg,dc=docker"                                                    
ldap_1      | 596eee85 conn=1026 op=1 RESULT tag=105 err=0 text=                                                                       
ldap_1      | 596eee85 conn=1026 op=2 UNBIND                                                                                           
ldap_1      | 596eee85 conn=1026 fd=16 closed                                                                                          
ldap_1      | ldapmodify: modify operation type is missing at line 22, entry "ou=people,dc=ldap,dc=ldap2pg,dc=docker"

ldap_1      | *** /container/run/startup/slapd failed with status 247                                                                  
```

Maybe we need a bit of documentation about seeding. That would be nice to accept `ldapadd` files.

**Comment by bersace** [comment]
@cgarnier README is updated. Please close the issue once you got it!

**Comment by osixia** [comment]
Version 1.1.9 allows you yo mount your ldif files to /container/service/slapd/assets/config/bootstrap/ldif/custom 
closing this :)

**Comment by cgarnier** [comment]
Nice =), Ty
