### ISSUE TITLE
LDAP_TLS_ENFORCE=true can't be reverted

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#127]
I am using [osixia/docker-openldap](https://hub.docker.com/r/osixia/openldap/) v1.1.8 and I expected the **LDAP_TLS_ENFORCE** to be revertable.

Following #91 #107 and commit https://github.com/osixia/docker-openldap/commit/6163e400f041926d2e9e6e93ef4cc132a947d685

From the Changelog the issue seems to be resolved but this commit comment the changes:

https://github.com/osixia/docker-openldap/commit/0578ede275c63c4123517646b552107090b66d3c

Apparently the fix isn't working since I still have this when trying to gain access on phpldapadmin: 

    error	Unable to connect to LDAP server ldap.service.consul
    Error: Confidentiality required (13) for user
    error	Failed to Authenticate to server
    Invalid Username or Password.

By setting `LDAP_LOG_LEVEL=256`, I can see the following in my openldap container : 

    /!\ WARNING: LDAP_TLS_ENFORCE=false but the container was previously started with LDAP_TLS_ENFORCE=true
    TLS enforcing can't be disabled once added. Ignoring LDAP_TLS_ENFORCE=false.
    Add TLS config...
    Add enforce TLS...
    Disable replication config...

I also tried like recommended in the [disable-tls](https://github.com/osixia/docker-openldap#disable-tls) instruction from  doc and this appear: 

    /!\ WARNING: LDAP_TLS=false but the container was previously started with LDAP_TLS=true
TLS can't be disabled once added. Ignoring LDAP_TLS=false.

- I wasn't aware of this warning before, maybe the `README.md` need to be updated ?
- Is it possible to recover my previous configuration ?

**Comment by osixia** [comment]
This is already in the README ;)
