### ISSUE TITLE
Anonymous and/or simple authentication bind

### ISSUE THREAD

**Issue by dalareo** [osixia/docker-openldap#134]
I am trying to connect to Openldap deployed using this project from Meteor, but the package I've found uses anonymous bind. Is it possible to setup anonymous bind with docker-openldap?

**Comment by osixia** [comment]
Hello,
anonymous auth is disabled in : https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/assets/config/bootstrap/ldif/02-security.ldif

2 options:
- define your own 02-security.ldif and mount it to /container/service/slapd/assets/config/bootstrap/ldif/02-security.ldif or extends the image and replace it.

- run the container with -e KEEP_EXISTING_CONFIG="true" this will not play boostrap config files and the container will get a default openldap debian config.
```
docker run -e KEEP_EXISTING_CONFIG="true" osixia/openldap
```

**Comment by dalareo** [comment]
Thanks!
And what about simple authentication, allowing all authenticated users to bind?

**Comment by osixia** [comment]
Simple authentication is already possible, but users can do nothing except on their entry.

**Comment by acearth** [comment]
How to modify 02-security.ldif ?   I tried mount  https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/assets/config/bootstrap/ldif/02-security.ldif into docker.

**Comment by doctorCC** [comment]
I am facing the same issue.  I simply want to turn on anonymous access so that anyone can see the users, but then they would need to know the users actual password to be given access.  I.e.  I want to use LDAP to hold the credentials and tell me if they are a member of a certain 'Group' or not.

**Comment by sandipb** [comment]
> I am facing the same issue. I simply want to turn on anonymous access so that anyone can see the users, but then they would need to know the users actual password to be given access. I.e. I want to use LDAP to hold the credentials and tell me if they are a member of a certain 'Group' or not.

This is what I did after setting up openldap, bootstrapping it, etc.

Create this file:
```ldif
dn: olcDatabase={1}{{ LDAP_BACKEND }},cn=config
changetype: modify
replace: olcAccess
olcAccess: to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * break
olcAccess: to attrs=userPassword,shadowLastChange by self write by dn="cn=admin,{{ LDAP_BASE_DN }}" write by anonymous auth by * none
olcAccess: to * by {{WHO}} read by dn="cn=admin,{{ LDAP_BASE_DN }}" write by * none
```
Replace:
1. `{{LDAP_BACKEND}}` with your setup, mine was `mdb`.
2. Replace `{{LDAP_BASE_DN}}` with your base DN.
3. Replace `{{WHO}}` (default value `self`) with `users` if you want all authenticated users to get readonly access, or `anonymous` if you want to allow anonymous auth. They will not see passwords obviously because of the previous line.

Run:
```shell-session
$ ldapmodify -x -D "cn=admin,cn=config" -H ldap://YOUR.LDAP.URL -f  security.ldif -W
modifying entry "olcDatabase={1}mdb,cn=config"
```
where `security.ldif` is the file you just created above. For the password prompt, use your config password ([`LDAP_CONFIG_PASSWORD`](https://github.com/osixia/docker-openldap#defaultstartupyaml))
