### ISSUE TITLE
Seeding ldap database with ldif do not work: "no write access to parent"

### ISSUE THREAD

**Issue by abinet** [osixia/docker-openldap#139]
Hi,

I'm trying to configure initial database using custom ldif file how it is proposed here:

```
docker run \
  --volume ./bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif \
  osixia/openldap:1.1.9 --copy-service

```

my 50-bootrap.ldif looks like:
```
    dn: ou=groups,dc=example,dc=org
    objectclass: organizationalUnit
    objectclass: extensibleObject
    objectclass: top
    ou: groups
    ....
```

But getting following exception:

```
adding new entry "ou=groups,dc=qio,dc=io"
ldap_add: Insufficient access (50)
	additional info: no write access to parent
```

If I understand it right, external authentication mechanism does not have write permissions for my newly created database. How it is intended to work?

**Comment by dbhorst** [comment]
Same problem here:
I made an ldif export with the osixia/phpldapadmin container and removed the first two entries (dc and admin user). My first entry that fails:
> dn: ou=Common,dc=test-company,dc=dir
> objectclass: organizationalUnit
> objectclass: top
> ou: Common
Debug log:

> Add custom bootstrap ldif...
> Processing file /container/run/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif
> 59a90392 conn=1024 fd=18 ACCEPT from PATH=/var/run/slapd/ldapi (PATH=/var/run/slapd/ldapi)
> 59a90392 conn=1024 op=0 BIND dn="" method=163
> 59a90392 conn=1024 op=0 BIND authcid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth"
> 59a90392 conn=1024 op=0 BIND dn="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" mech=EXTERNAL sasl_ssf=0 ssf=71
> 59a90392 conn=1024 op=0 RESULT tag=97 err=0 text=
> 59a90392 conn=1024 op=1 ADD dn="ou=Common,dc=test-company,dc=dir"
> 59a90392 conn=1024 op=1 RESULT tag=105 err=50 text=no write access to parent
> 59a90392 conn=1024 op=2 UNBIND
> 59a90392 conn=1024 fd=18 closed
> ldap_add: Insufficient access (50)
> 	additional info: no write access to parent
> adding new entry "ou=Common,dc=test-company,dc=dir"
> 59a90392 daemon: shutdown requested and initiated.
> 59a90392 slapd shutdown: waiting for 0 operations/tasks to finish
> *** /container/run/startup/slapd failed with status 50

**Comment by abinet** [comment]
No, the problem is that ldapadd container call is using EXTERNAL mechanism of authentication and ETERNAL is not allowed to modify parent.

I've got this working with ldapmodify. To trigger this you must have    "changetype: add" attribute in the config:

dn: ou=Common,dc=test-company,dc=dir
changetype: add
objectclass: organizationalUnit
objectclass: top
ou: Common

**Comment by osiloke** [comment]
I had this same issue. In my case, i had dangling spaces. The ldif files seem to follow a very strict syntax

**Comment by dbhorst** [comment]
Adding "changetype: add" helped.
The error still exists in the logs, but then a different method is used to authenticate, that worked.
