### ISSUE TITLE
Docker-openldap set IP

### ISSUE THREAD

**Issue by tsaenger81** [osixia/docker-openldap#140]
Hello 
i would like to give the Docker a static IP but i can not use --ip 172.17.0.2.
I get the Message: 
docker: Error response from daemon: User specified IP address is supported on user defined networks only.

What happends?

Thanks a lot

best regards
tobias

**Comment by tsaenger81** [comment]
i solved it by creating my own interface

**Comment by osixia** [comment]
Hello,
thanks for your feedback.

I'm closing this issue related to docker and not directly to this image.
