### ISSUE TITLE
ldap networking?

### ISSUE THREAD

**Issue by d3nd0h** [osixia/docker-openldap#15]
Hello, I am currently trying to use openldap with kaiwa-server (https://github.com/digicoop/kaiwa-server)
It uses prosody xmpp server and trying to use ldap to improve scalability (if I got it right). My problem is when I try to add user from the server using command prosodyctl it shows an error
```bash
lua5.1: /usr/lib/prosody/modules/ldap.lib.lua:217: attempt to index local 'ld' (a nil value)
stack traceback:
	/usr/lib/prosody/modules/ldap.lib.lua:217: in function </usr/lib/prosody/modules/ldap.lib.lua:211>
	(tail call): ?
	(tail call): ?
	(tail call): ?
	/usr/bin/prosodyctl:305: in function '?'
	/usr/bin/prosodyctl:1247: in main chunk
	[C]: ?
```
after I inspect the file /usr/lib/prosody/modules/ldap.lib.lua
ld is a connection to ldap server but it doesn't get any connection. I don't know which part is wrong whether it's my docker or the ldap server.

And another thing when I tried to figure out ldap server ip address using ifconfig inside the docker container it return unknown command :( and also no editor i could use inside it. Is this bug or meant to be like this?

Thank you and sorry for the long post :)

PS:
I create the docker container using this command:
```bash
docker run -d \
     --name ldap \
     -p 389:389 -p 636:636\
     -v /home/fendy/kaiwa-server-master:/home \
     -e LDAP_DOMAIN=localhost \
     -e LDAP_ORGANISATION=MyOrganisation \
     -e LDAP_ROOTPASS=mypassword \
     osixia/openldap
```

**Comment by osixia** [comment]
Hello,
LDAP_ROOTPASS variable doesn't exists in this image use LDAP_ADMIN_PASSWORD instead. 
Please check readme file "Environment Variables" section.

So i guess you didn't use the right ldap password in the kaiwa-server image.

if you want to get the ip of a container you can use the `docker inspect` command.
Or if you are running a terminal inside the container with `hostname -i` 

Sorry but there is no text editor inside the container to make it as light as possible.

**Comment by d3nd0h** [comment]
Thanks for the reply!

I solved my problem (apparently) it was docker problem (due to my lack of understanding about docker --link option). The kaiwa-server container created before I create the openLDAP container.
So the kaiwa-server was linked to old ldap container's IP address. I almost break my laptop because of this xD. As result of that kaiwa-server couldn't get connection to the ldap server.

I really appreciate your help and I'm sorry because I think this is off topic for asking the docker issue.

**Comment by osixia** [comment]
you're welcome
