### ISSUE TITLE
[RFC][Feature] Adding LDAP_PORT and LDAPS_PORT to configuration env

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#165]
I want to deploy many `docker-openldap` on a Mesos cluster. 

We use internally HAproxy for TCP reverse proxy [See: here](https://github.com/eBayClassifiedsGroup/PanteraS#put-service-into-haproxy-tcp-load-balancer).

At this step, I do not know the forward port elected by marathon, and the HAproxy is using the `servicePort`.

Because the haproxy port is unique, this feature would add possibility to switch the local port used by `docker-openldap` for `ldap://` and `ldap://`

The environment variables would be: 

- `LDAP_PORT` : set `ldap://` port (default: 389)
- `LDAPS_PORT` : set `ldaps://` port (default: 389)

**Comment by urzds** [comment]
This might also help with running OpenLDAP as a regular user, without root permissions. (See e.g. #109 for an example where this might be handy.)

**Comment by colearendt** [comment]
Another use case for this - we have hard restrictions on port numbers being > 1024 in one of my kubernetes-based environments, so not being able to easily customize the port has caused a good bit of pain.
