### ISSUE TITLE
LDAP_ADMIN_PASSWORD with space breaks container setup

### ISSUE THREAD

**Issue by wijata** [osixia/docker-openldap#167]
just try setting up
LDAP_ADMIN_PASSWORD to "foo bar" value
probbaly same for LDAP_CONFIG_PASSWORD

**Comment by goeland86** [comment]
What exactly did you use as your command when setting it up? I'd have expected that if you put the quotes around the password it would be set with the space taken into account. Like so:
docker run --env LDAP_ORGANISATION="My Company" --env LDAP_DOMAIN="my-company.com" \
--env LDAP_ADMIN_PASSWORD="Jon Sn0w" --detach osixia/openldap:1.1.11

**Comment by wijata** [comment]
I actually left the project, but as I remember there are following codes in startup.sh file, try replacing password with two words
slappasswd -s $LDAP_CONFIG_PASSWORD
ldapmodify -h localhost -p 389 -D cn=admin,$LDAP_BASE_DN -w $LDAP_ADMIN_PASSWORD -f $LDIF_FILE

**Comment by goeland86** [comment]
I'd guess it's a small bug related to improper escaping of the password variable. It should have the quotes around it, like so:
`ldapmodify -h localhost -p 389 -D cn=admin,"$LDAP_BASE_DN" -w "$LDAP_ADMIN_PASSWORD" -f "$LDIF_FILE"`

Tricky little bash idiosyncracies...
