### ISSUE TITLE
Error when volume mounting with docker-compose

### ISSUE THREAD

**Issue by michelvosje** [osixia/docker-openldap#180]
I used the following docker-compose file:

> version: '2'
services:
  open_ldap:
    image: 'osixia/openldap:latest'
    container_name: 'openldap'
    ports:
     - ${LDAP_PORT}:389
    volumes:
     - ./data/database:/var/lib/ldap
     - ./data/config:/etc/ldap/slapd.d
    environment:
     - LDAP_ORGANISATION=${LDAP_ORGANISATION}
     - LDAP_DOMAIN=${LDAP_DOMAIN}
     - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
     - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}

This will generate the following error:

> $ docker-compose up
Creating openldap ...
Creating openldap ... done
Attaching to openldap
openldap     | *** CONTAINER_LOG_LEVEL = 3 (info)
openldap     | *** Search service in CONTAINER_SERVICE_DIR = /container/service :
openldap     | *** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
openldap     | *** link /container/service/slapd/startup.sh to /container/run/startup/slapd
openldap     | *** link /container/service/slapd/process.sh to /container/run/process/slapd/run
openldap     | *** Set environment for startup files
openldap     | *** Environment files will be proccessed in this order :
openldap     | Caution: previously defined variables will not be overriden.
openldap     | /container/environment/99-default/default.startup.yaml
openldap     | /container/environment/99-default/default.yaml
openldap     |
openldap     | To see how this files are processed and environment variables values,
openldap     | run this container with '--loglevel debug'
openldap     | *** Running /container/run/startup/:ssl-tools...
openldap     | *** Running /container/run/startup/slapd...
openldap     | Database and config directory are empty...
openldap     | Init new ldap server...
openldap     | invoke-rc.d: could not determine current runlevel
openldap     | invoke-rc.d: policy-rc.d denied execution of stop.
openldap     |   Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.44+dfsg-5+deb9u1... done.
openldap     |   Creating initial configuration... done.
openldap     |   Creating LDAP directory... failed.
openldap     | **Loading the initial configuration from the ldif file () failed with
openldap     | the following error while running slapadd:**
openldap     |     5a4e2eab bdb(dc=example,dc=org): BDB0126 mmap: Invalid argument
openldap     |     5a4e2eab hdb_db_open: database "dc=example,dc=org" cannot be opened, err 22. Restore from backup!
openldap     |     5a4e2eab bdb(dc=example,dc=org): BDB1566 txn_checkpoint interface requires an environment configured for the transaction subsystem
openldap     |     5a4e2eab bdb_db_close: database "dc=example,dc=org": txn_checkpoint failed: Invalid argument (22).
openldap     |     5a4e2eab backend_startup_one (type=hdb, suffix="dc=example,dc=org"): bi_db_open failed! (22)
openldap     |     slap_startup failed
openldap     | *** /container/run/startup/slapd failed with status 1
openldap     |
openldap     | *** Killing all processes...
openldap exited with code 0

If i remove the "volumes" section from the docker-compose.yml i won't get the error and everything works correctly.

I run this on Windows using Docker Quickstart Terminal. Not sure but i think it's called Docker Toolbox for Windows.

**Comment by michelvosje** [comment]
Does this have something to do with the "--copy-service" argument? If so. How do i pass the argument using docker-compose.yml?

**Comment by parideis** [comment]
You can pass arguments in a docker compose file by using **command**.
**command: --copy-service**

**Comment by michelvosje** [comment]
I changed the compose file so it uses named volumes and now it works.
