### ISSUE TITLE
ReOpenLDAP

### ISSUE THREAD

**Issue by denji** [osixia/docker-openldap#185]
> OpenLDAP with a lot of heisenbugs fixing, mostly for replication

* https://github.com/leo-yuriev/ReOpenLDAP
  * https://ldapcon.org/2017/wp-content/uploads/2017/08/1_ReOpenLDAP-LDAPCON-2017.pdf

#### Features (major):
 * multi-master replication is working properly and robustly (it seems no other LDAP server can do this)
 * `reopenldap [iddqd] [idkfa] [idclip]`
 * `quorum { [vote-sids ...] [vote-rids ...] [auto-sids] [auto-rids] [require-sids ...] [require-rids ...] [all-links] }`
 * `quorum limit-concurrent-refresh`
 * `biglock { none | local | common }`
 * storage (mdbx): dreamcatcher & oom-handler (ITS#7974)
 * storage (mdbx): lifo & coalesce (ITS#7958)
 * storage (mdbx): steady & weak datasync
 * bundled with all known contributed modules/overlays/plugins

#### Features (minor):
 * `syncprov-showstatus { none | running | all }`
 * `crash-backtrace on|off`
 * `coredump-limit <mbytes>`
 * `memory-limit <mbytes>`
 * checkpoints by volume-of-changes and periodically in seconds
 * syncrepl's `requirecheckpresent` option
 * `keepalive <idle>:<probes>:<interval>` for incoming connections
 * built-in memory checker, including ls-malloc
 * ready for AddressSanitizer and Valgrind
 * ready for LTO (Link-Time Optimization) by GCC and clang
 * support for OpenSSL 1.1.x, Mozilla NSS, GnuTLS and LibreSSL 2.5.x

#### Fixes:
 * all from openldap/master and openldap/2.4 branches
 * a lot for replication, especially for multi-master
 * removed ~5K warnings from GCC/clang
 * removed ~1K warnings from ThreadSanitizer (a data race detector)
 * removed most of memory leaks (tests could be passed under Valgrind)
 * checked with PVS-Studio static analyser, [see details](https://github.com/leo-yuriev/ReOpenLDAP/issues/107)
 * <a href="https://scan.coverity.com/projects/reopen-reopenldap"><img alt="Coverity Scan Build Status" src="https://scan.coverity.com/projects/6972/badge.svg"/></a>

**Comment by denji** [comment]
@BertrandGouny

Codebase ReOpenLDAP includes all bug-fixes and improvements of the parent OpenLDAP. Branch master is kept stable and meets OpenLDAP/2.4.x, with the addition of the individual improvements from OpenLDAP/master. The branch next meets the following versions OpenLDAP/2.5.x.

The main difference ReOpenLDAP — work without crashes and without failure of service under high load with replication in multi-master clusterthat was previously impossible. Our tests, including load, clearly show that ReOpenLDAP ready for commercial operation, and the original OpenLDAP, unfortunately, is still there.

It was fixed more than a dozen heisenbugsthat existed over the years. For example, one of the problems was officially nearly 7 years. Another problem has existed undetected for over 5 years and was the cause of the loss changes during replication.

In addition, we made several significant fixes and improvements to the replication mechanism that is particularly relevant for multi-master cluster. To research and resolve issues in syncprov/sycnrepl we had to spend almost a year. The summer of 2016 ReOpenLDAP correctly replicates according to RFC4533, including mirror (multi-master) mode. Unfortunately the original OpenLDAP while still may lose part of change and even remove a lot of the necessary records that is why probabilistic failures of their own tests.

**Comment by denji** [comment]
@BertrandGouny https://github.com/leo-yuriev/ReOpenLDAP/tree/devel/contrib/docker

**Comment by EugenMayer** [comment]
IMHO, to be honest, thats something for a different image isn't? This image is about openldap (the original) and thats what is then expected, when suddenly a fork gets used... thats just not what it is meant to be.

For myself, if this image would switch to reopenldap, i would fork it and get it back to openldap.

What about @denji you just create a long-time fork of this, where you upstream merge the changes, but changes the package installed instead of replacing this image - i think this would create more value then just having one - people can chose from either of this.

Sure @BertrandGouny could just publish to images from within here, which will mean, he will support both ( more effort ) - i could imagine thats a little over the top

**Comment by denji** [comment]
@EugenMayer Who told you that replication implementation in OpenLDAP is production ready? In this repository, are there issues related to falling replication.

> The reason for the creation of the fork was the refusal to include a number of fixes in the main OpenLDAP because of the desire to maintain compatibility with older C compilers (compatibility with compilers without support for variable macros, which appeared in the C99 standard, was violated in only one patch from a large series of fixes). After the fork ReOpenLDAP master branch is kept stable and meets OpenLDAP/2.4.x, with the addition of individual improvements from OpenLDAP / master. Branch ReOpenLDAP next corresponds to the following version of OpenLDAP/2.5.x.
