### ISSUE TITLE
Error while loading shared libraries: libldap_r-2.4.so.2

### ISSUE THREAD

**Issue by Dekedro** [osixia/docker-openldap#189]
Hi, I get this error when trying to run openldap:

```
...
Start OpenLDAP...
slapd: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: Permission denied
*** /container/run/startup/slapd failed with status 127

*** Killing all processes...
```

Command: `docker run -d osixia/openldap:1.1.11`
Host: Ubuntu 16.04

**Comment by BertrandGouny** [comment]
Hi,
can you provide `docker info` outputs ?

**Comment by Dekedro** [comment]
After rebooting server I can no longer reproduce issue. So I guess `docker info` won't be much of a help. Anyway, thanks for your concern.
