### ISSUE TITLE
Re-running container with volumes won't start

### ISSUE THREAD

**Issue by mikejortiz1** [osixia/docker-openldap#19]
If I re run the container with exposed volumes it never starts up.  In the log for the container I get this 
*** Running /etc/my_init.d/slapd...
Starting openldap...
*** /etc/my_init.d/slapd failed with status 1

*** Killing all processes..

**Comment by ofreax** [comment]
I can't reproduce, do you have an example?

**Comment by NickG123** [comment]
I am experiencing a similar issue.  I run the container, stop it, remove it, and then run it again with the same (hosted) volumes.  I then receive the same error message as above.

I am suspicious of the following line:
FIRST_START_DONE="/etc/docker-openldap-first-start-done"

This file is not placed in the volume, so when the new docker container is created, it does not contain this file.  As far as I can tell, the container attempts to create the new directory, but fails somewhere along the line.

**Comment by NickG123** [comment]
I can confirm that moving the "docker-openldap-first-start-done" file into a volume resolves the issue with restart.

**Comment by osixia** [comment]
Hello @NickG123,
thanks it's it's clearer put that way.

I'll fix that asap.

**Comment by osixia** [comment]
Sorry but i don't have the issue, so i can't fix that without an example.

**Comment by kuhnroyal** [comment]
Same thing here.

**Comment by osixia** [comment]
Good guys but if nobody give me an example of what your are doing precisely it won't help

**Comment by NickG123** [comment]
Sorry, I've been a bit busy.
I just tried a simple example and it seemed to work fine, so it must be one of the options I'm using.
Here is the full command I use to run my container (with private information removed):

docker run -h ldap1.example.com -e LDAP_ORGANISATION="example" -e LDAP_DOMAIN="example.com" -e LDAP_REPLICATION=true -e LDAP_REPLICATION_HOSTS="['ldap://ldap1.example.com', 'ldap://ldap2.example.com']" -e LDAP_READONLY_USER=true -e LDAP_TLS_PROTOCOL_MIN=3.0 -e LDAP_TLS_CIPHER_SUITE=NORMAL -e LDAP_TLS_VERIFY_CLIENT=never -v /data/ldap/var:/var/lib/ldap -v /data/ldap/etc:/etc/ldap/slapd.d -v /data/ldap/certs:/container/service/slapd/assets/certs -p 389:389 -p 636:636 -d --name ldap osixia/openldap

Essentially, I run the above command, wait until completion, stop the container, remove the container, and then run the above command again, and then receive the error.

**Comment by osixia** [comment]
Thanks @NickG123 ,
i just pushed a new version of the image : 1.0.3
can you confirm that it fixes the issue ?
