### ISSUE TITLE
Docker VOLUME is not needed to be able to stop a container without losing data

### ISSUE THREAD

**Issue by bbc2** [osixia/docker-openldap#2]
In `README.md`, I can read:
> The directories /var/lib/ldap (LDAP database files) and /etc/ldap/slapd.d (LDAP config files) has been declared as volumes, so your ldap files are saved outside the container in data volumes.
>
> This mean that you can stop, and restart the container and get back your ldap without losing any data.

From https://docs.docker.com/reference/builder/#volume, I learn that having a folder declared as a volume just means that Docker will create a mount point for it.  Therefore, it won't be part of any of my container's layers.

It will also persist through a stop-start cycle, but so will other data:
```bash
> docker run -ti debian:jessie /bin/bash
root@c1e0e7fecb8c:/# echo Hello World > myfile
root@c1e0e7fecb8c:/# exit
> docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
c1e0e7fecb8c        debian:jessie       "/bin/bash"         25 seconds ago      Exited (0) 3 seconds ago                       clever_engelbart    
> docker start clever_engelbart
clever_engelbart
> docker attach clever_engelbart
root@c1e0e7fecb8c:/# 
root@c1e0e7fecb8c:/# cat myfile 
Hello World

**Comment by osixia** [comment]
Hello,
that's right, thank you for reporting this mistake. 

I'll fix the readme accordingly.
