### ISSUE TITLE
LDAP_REPLICATION=True kills container, slapd: "no serverID / url match found"

### ISSUE THREAD

**Issue by aryadrottning** [osixia/docker-openldap#203]
1. OS - CentOS 7
2. Docker Version
`Docker version 17.09.1-ce, build 19e2cf6
`

How to reproduce:

1. https://github.com/osixia/docker-openldap#multi-master-replication

```
LDAP_CID=$(docker run --hostname ldap.myrealdomain.com --env LDAP_REPLICATION=true --detach osixia/openldap:1.2.0)`
Logs:

[root@ldap:~]# LDAP_CID=$(docker run --hostname ldap.mydomain.com --env LDAP_REPLICATION=true  osixia/openldap:1.2.0)
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml
/container/environment/99-default/default.startup.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of stop.
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.44+dfsg-5+deb9u1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
config file testing succeeded
2018/04/09 11:35:21 [INFO] generate received request
2018/04/09 11:35:21 [INFO] received CSR
2018/04/09 11:35:21 [INFO] generating key: ecdsa-384
2018/04/09 11:35:21 [INFO] encoded CSR
2018/04/09 11:35:21 [INFO] signed certificate with serial number 59717248882709523324435026876626682989678504384
*** Set environment for container process
*** Remove file /container/environment/99-default/default.startup.yaml
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/process/slapd/run...
5acb4ffa @(#) $OpenLDAP: slapd  (Aug 10 2017 19:12:46) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5acb4ffa read_config: no serverID / URL match found. Check slapd -h arguments.
5acb4ffa slapd stopped.
5acb4ffa connections_destroy: nothing to destroy.
*** /container/run/process/slapd/run exited with status 1
*** Killing all processes...
```

```
Without env LDAP_REPLICATION:

*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml
/container/environment/99-default/default.startup.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of stop.
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.44+dfsg-5+deb9u1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
config file testing succeeded
2018/04/09 11:40:04 [INFO] generate received request
2018/04/09 11:40:04 [INFO] received CSR
2018/04/09 11:40:04 [INFO] generating key: ecdsa-384
2018/04/09 11:40:04 [INFO] encoded CSR
2018/04/09 11:40:04 [INFO] signed certificate with serial number 107420275298105567103065320129946934699086714795
*** Set environment for container process
*** Remove file /container/environment/99-default/default.startup.yaml
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/process/slapd/run...
5acb5114 @(#) $OpenLDAP: slapd  (Aug 10 2017 19:12:46) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
TLS: warning: ignoring dhfile
5acb5115 slapd starting
```

**Comment by aryadrottning** [comment]
Hey. It worked now, could I request update to multimaster quick start example?

Also starting with Auto TLS shows this:

```
5acb7f22 slap_client_connect: URI=ldap://DELETED DN="cn=admin,dc=domain,dc=pl" ldap_sasl_bind_s failed (-1)
5acb7f22 do_syncrepl: rid=102 rc -1 retrying
5acb7f22 slap_client_connect: URI=ldap://DELETED DN="cn=admin,cn=config" ldap_sasl_bind_s failed (-1)
5acb7f22 do_syncrepl: rid=002 rc -1 retrying
```

Beside that sync does not work properly. Currently I'm looking for a quick workaround.

**Comment by BertrandGouny** [comment]
Yes of course :)

**Comment by aryadrottning** [comment]
Closing this issue since LDAP_REPLICATION_HOSTS env is mandatory. Will probably open new one due sync & tls errors.

**Comment by 2030405043** [comment]
Hi 
log appears when I turn on the LDAP_REPLICATION_HOSTS and LDAP_REPLICATION=true parameters

Start OpenLDAP...
Waiting for OpenLDAP to start...
5d54fb12 @(#) $OpenLDAP: slapd  (Feb  9 2019 17:02:42) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5d54fb12 daemon: bind(9) failed errno=99 (Cannot assign requested address)
5d54fb12 read_config: no serverID / URL match found. Check slapd -h arguments.
5d54fb12 slapd stopped.
5d54fb12 connections_destroy: nothing to destroy.

What is the cause of this ? plase

**Comment by thebodzio** [comment]
Feeling like a necromancer, but, oh, well…

I think there's a major problem with the way replication is treated on container creation, unless KEEP_EXISTING_CONFIG is set to true.

Let's assume the following: we have existing configuration, database and certificates on volumes mounted on the container creation. If configuration already contains `olcServerID` attributes it will basically force slapd to have a matching value in `-h` parameter. It's all fine if container's FQDN was set accordingly and KEEP_EXISTING_CONFIG is true. However if it is false it goes on to check if config contains a file with PREVIOUS_HOSTNAME variable set:

https://github.com/osixia/docker-openldap/blob/635034a75878773f8576d646422cf26e43741fab/image/service/slapd/startup.sh#L270-L280

It, rather intelligently, sets PREVIOUS_HOSTNAME_PARAM to allow for replication reconfiguration, in case user changed the hostname. The unfortunate thing is that the PREVIOUS_HOSTNAME_PARAM is used… nowhere. Especially not in the following fragment:

https://github.com/osixia/docker-openldap/blob/635034a75878773f8576d646422cf26e43741fab/image/service/slapd/startup.sh#L306-L313

where slapd is started up to accept configuration changing LDIFs generated next. Hence the `no serverID / URL match found. Check slapd -h arguments` error. But there are more potential problems here. `olcServerID` may be set to `ldaps://` and end up with port number (e.g. `ldaps://ldap1.example.org:3636`).

OpenLDAP administration guide says the following:

> Note: As stated in slapd-config(5), URLs specified in olcSyncRepl directives are the URLs of the servers from which to replicate. These must exactly match the URLs slapd listens on (-h in Command-Line Options). Otherwise slapd may attempt to replicate from itself, causing a loop. 

It looks like the same is true about `olcServerID`.

If was just about my own “exotic”(?) configuration, I'd be content with KEEP_EXISTING_CONFIG, but this may well prevent replication from being reconfigured whenever previously defined replication left its trace in `cn=config`.

process.sh seems to do it right:

https://github.com/osixia/docker-openldap/blob/635034a75878773f8576d646422cf26e43741fab/image/service/slapd/process.sh#L12-L16

Just my 2¢. I hope it helps :}

**Comment by thebodzio** [comment]
Just a recent thought: why not just use `slapadd`?
