### ISSUE TITLE
Getting server-side TLS logs

### ISSUE THREAD

**Issue by n-b-sonar** [osixia/docker-openldap#22]
Hi there,

First things first: thanks a lot for a great docker project. Saved me tons of time and really easy to use (especially with the phpldapadmin project counterpart !).

I'm struggling with connecting over ldaps from a Java client (works better with *openssl s_client*) and would like to get the detailed handshake trace on the ldap side. Any recommendation on how I can achieve that ? (I'm stuck at getting any log from the container itself)

Thanks a lot,
Nicolas

P.S.: my Java client is failing during handshake, server is closing the connection for some reason (any ideas are welcome)
```
localhost-startStop-1, received EOFException: error
localhost-startStop-1, handling exception: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
```

**Comment by n-b-sonar** [comment]
Guess I had to write a post to finally see the light. Figured out I could just attach to the container and see the logs in the output. With that:

```TLS: can't accept: Could not negotiate a supported cipher suite..```

Saw that there's [https://github.com/osixia/docker-openldap/issues/17](another post on this topic), I'll try out the suggestions mentioned there.

Thanks

**Comment by n-b-sonar** [comment]
Using `LDAP_TLS_CIPHER_SUITE=NORMAL` allowed me to successfully go through the SSL HandShake.

**Comment by osixia** [comment]
:)
