### ISSUE TITLE
no permission error in container logs

### ISSUE THREAD

**Issue by wmfairuz** [osixia/docker-openldap#23]
Hi, 
I try to run the container using

```
 docker run -d osixia/openldap
```

But got below error instead (from docker logs)

```
[root@docker01 ~]# docker logs naughty_nobel
Execute /container/tool/my_init --skip-runit bash /etc/service/slapd/run
*** Running /etc/my_init.d/slapd...
database and config directory are empty
-> set bootstrap config
invoke-rc.d: policy-rc.d denied execution of stop.
slappasswd: error while loading shared libraries: cannot restore segment prot after reloc: Permission denied
  Creating initial configuration... Loading the initial configuration from the ldif file () failed with
the following error while running slapadd:
    slapadd: error while loading shared libraries: cannot restore segment prot after reloc: Permission denied
*** /etc/my_init.d/slapd failed with status 1

*** Killing all processes...
```

**Comment by osixia** [comment]
On which environment to you run this ?

**Comment by wmfairuz** [comment]
Fedora release 22 (Twenty Two)
Docker version 1.7.0.fc22, build 74e7a7a/1.7.0

**Comment by ygotame** [comment]
slappasswd: error while loading shared libraries: cannot restore segment prot after reloc: Permission denied
  Creating initial configuration... Loading the initial configuration from the ldif file () failed with
the following error while running slapadd:
    slapadd: error while loading shared libraries: cannot restore segment prot after reloc: Permission denied

I am using : Docker 1.8.2 and Centos 7 64bit

By doing some research, I found out that it could be because of SELinux not disable on the OS. I guess ?

Thank's

**Comment by osixia** [comment]
Hi, did you tried : 
http://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker 

is that change something ?

**Comment by ygotame** [comment]
I will check that and let you know. Thank's for the update.

**Comment by brady-vitrano** [comment]
Running the docker container with `--privileged=true` resolves this issue. I would prefer a non-privileged container. Anyone have suggestions?

My version of Docker was installed with `yum install kubernetes`

```
Client:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64
```
