### ISSUE TITLE
[Bug] Improve reconfiguration, upgrading and restore

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#246]
Dear all,

I am a user of [osixia/docker-openldap](https://github.com/osixia/docker-openldap) since 3 year's and I can have a good feedback about it.

I have been implementing a public instance and this is why it was one of my most difficult containers to maintain:

## Certificates

Certificates can't have long name, we must rename them when mounting to the container.
This at first forced us to rename the certificates during the mapping, but now that we use a standardized way of mounting volumes, this is not possible.

I suggest that shortname certificates should be created at start and not be part of the application configuration. (use `cp` in startup script).

## Upgrade

Upgrading  [osixia/docker-openldap](https://github.com/osixia/docker-openldap) was the worst step we have. We do not use data container. The container [osixia/docker-openldap](https://github.com/osixia/docker-openldap) container is started with mounted volumes.

Because of the no long name certificates, we have seen many times our upgrade failing and it as been always hard to debug why.

Most of the time, we end up doing an export of our running ldap database, and reimport it using a fresh deployment. 

This can become messy when we just need to start on a different host. We have nout found any reliable way to update the configuration and to perform upgrade.

## Conclusion

This image is not really production stable. Data should be safe so does restarting.

If anyone has a nice procedure to prevent this. Sort of bug, I am now rexporting all my database for doing the upgrade. It takes times and precaution. 

I might try to fixe the certificates issues as this is really dumb but I'd like to get your opinion. How do you people manage to Upgrade and restore safely?

**Comment by BertrandGouny** [comment]
Sush dramatic issue title for a long certificate name problem if i understand ?

Please take care to update the title to the real issue description, and provide steps to reproduce the issue.

**Comment by kopax** [comment]
@BertrandGouny I did the dramatic title on purpose. 

I see you [known security issue](https://github.com/osixia/docker-openldap/#known-security-issues), why not have a "known issue"? I'm struggling often on migrating data and configuration.

I will override the startup script of the image in order to improve the edition of the certificate using a `tmp` boot directory. 

- `LDAP_TLS_CRT_FILENAME`: Ldap ssl certificate filename. Defaults to ldap.crt
- `LDAP_TLS_KEY_FILENAME`: Ldap ssl certificate private key filename. Defaults to ldap.key
- `LDAP_TLS_CA_CRT_FILENAME`: Ldap ssl CA certificate filename. Defaults to ca.crt
- `LDAP_TLS_DIRECTORY`: Ldap ssl directory use at boot to find and copy certificate

`Dockerfile`:

```Dockerfile
ADD container/tool/copy-certificate.sh /container/tool/copy-certificate
ADD container/tool/run-ssl-fixed.sh /container/tool/run-ssl-fixed

ENTRYPOINT ["/container/tool/run-ssl-fixed"]
```

`run-ssl-fixed`:

```bash
#!/usr/bin/env bash
set -e

/container/tool/copy-certificates
/container/tool/run

exit 0
```

`copy-certificate`

```bash
#!/usr/bin/env bash
set -e
echo "copy certificates..."
LDAP_TLS_DIRECTORY=${LDAP_TLS_DIRECTORY:-"/container/tmp/certs"}
tls_dest_directory="/container/service/slapd/assets/certs"
if [[ ! -z ${LDAP_TLS_CRT_FILENAME} ]]; then
  cp "${LDAP_TLS_DIRECTORY}/${LDAP_TLS_CRT_FILENAME}" "${tls_dest_directory}/crt.pem"
fi
if [[ ! -z ${LDAP_TLS_KEY_FILENAME} ]]; then
  cp "${LDAP_TLS_DIRECTORY}/${LDAP_TLS_KEY_FILENAME}" "${tls_dest_directory}/key.pem"
fi
if [[ ! -z ${LDAP_TLS_CA_CRT_FILENAME} ]]; then
  cp "${LDAP_TLS_DIRECTORY}/${LDAP_TLS_CA_CRT_FILENAME}" "${tls_dest_directory}/ca.pem"
fi

exit 0
```

If you prefer a different pattern just say it, please.

To me, the image is not production safe, this risk of breaking the configuration is high and manual fixe is not recommended because not for everyone. Most people start the docker container once while this image requires some knowledge and manual administration. 

I offer to improve and fix. This is called contributing. I will test locally if anyone had similar issues with this container management just say it here.

**Comment by kopax** [comment]
I have fixed this on my image.

**Comment by michidk** [comment]
Is this image public? Mind to share?

**Comment by kopax** [comment]
It's not public I also added my bootstrap conf in it, did not think to release a public image.

I thought the appropriate way was to correct this in the image but the author @BertrandGouny just told it was not that important.

For your concern, this is how you can solve this:

```Dockerfile
FROM osixia/openldap:1.2.1

ARG BUILD_ORG
ENV BUILD_ORG=${BUILD_ORG:-"default"}
ARG BUILD_ENV
ENV BUILD_ENV=${BUILD_ENV:-"dev"}

# Osixia/OpenLDAP extension
ADD bootstrap/${BUILD_ORG} /container/service/slapd/assets/config/bootstrap
ADD environment/${BUILD_ENV} /container/environment/01-custom

ADD container/tool/copy-certificate.sh /container/tool/copy-certificate
ADD container/tool/run-ssl-fixed.sh /container/tool/run-ssl-fixed

ENTRYPOINT ["/container/tool/run-ssl-fixed"]
```
