### ISSUE TITLE
LDAP_BASE_DN needs to be defined

### ISSUE THREAD

**Issue by tobikris** [osixia/docker-openldap#282]
This morning my containers wouldn't start after an update and reboot. It took me quite a while to find out that the problem was a missing LDAP_BASE_DN definition. Before it worked without an explicit definition in docker-compose.yml.

**Comment by lsampaioweb** [comment]
I'm having the same problem. What did you do to fix the problem?

**Comment by lsampaioweb** [comment]
> This morning my containers wouldn't start after an update and reboot. It took me quite a while to find out that the problem was a missing LDAP_BASE_DN definition. Before it worked without an explicit definition in docker-compose.yml.

I added content on LDAP_BASE_DN and now it works!! Thanks!

**Comment by obourdon** [comment]
[
https://github.com/osixia/docker-openldap/issues/283](
https://github.com/osixia/docker-openldap/issues/283) was fixed today and code merged into 1.2.4-dev

**Comment by obourdon** [comment]
@tobikris may be this issue can now be closed ?
