### ISSUE TITLE
how to restart osixia/openldap image with volumes mounted?

### ISSUE THREAD

**Issue by zohaibscytale** [osixia/docker-openldap#286]
I am running osixia/openldap and osixia/phpldapadmin (volumes mounted) with these commands :

docker run -p 389:389 -p 636:636 --name ldap-service --volume /data/slapd/database:/var/lib/ldap --volume /data/slapd/config:/etc/ldap/slapd.d --hostname ldap-service --detach osixia/openldap:1.2.3 --copy-service --loglevel debug

docker run --name phpldapadmin-service --hostname phpldapadmin-service --link ldap-service:ldap-host --env PHPLDAPADMIN_LDAP_HOSTS=ldap-host --detach osixia/phpldapadmin:0.7.2

On the first run it starts but on restarting the servers with the same command I got the error

    /container/run/startup/slapd failed with status 34
    whereas status 34 refers to LDAP_INVALID_DN_SYNTAX

could not be able to find a solution for this. Any help?

**Comment by obourdon** [comment]
@zohaibscytale [
https://github.com/osixia/docker-openldap/issues/283](
https://github.com/osixia/docker-openldap/issues/283) has been solved and fixed was merged today in 1.2.4-dev
