### ISSUE TITLE
Error during startup on Azure container instances

### ISSUE THREAD

**Issue by vidarkongsli** [osixia/docker-openldap#287]
I am trying to run the image in Azure container instances. When set the ports 389, 636 in Azure, the slapd daemon fails to start properly. Here's a typical excerpt from the logs:

```
5c633883 slapd starting
5c633885 conn=1000 fd=12 ACCEPT from IP=10.240.255.55:56972 (IP=0.0.0.0:389)
5c633885 conn=1001 fd=13 ACCEPT from IP=10.240.255.55:56973 (IP=0.0.0.0:636)
5c633888 conn=1002 fd=14 ACCEPT from IP=10.240.255.56:52524 (IP=0.0.0.0:389)
5c633888 conn=1003 fd=15 ACCEPT from IP=10.240.255.56:52522 (IP=0.0.0.0:636)
TLS: can't accept: The TLS connection was non-properly terminated..
5c63388b conn=1001 fd=13 closed (TLS negotiation failure)
5c63388b conn=1000 fd=12 closed (connection lost)
5c63388b conn=1004 fd=12 ACCEPT from IP=10.240.255.55:57142 (IP=0.0.0.0:389)
5c63388b conn=1005 fd=13 ACCEPT from IP=10.240.255.55:57141 (IP=0.0.0.0:636)
5c63388e conn=1002 fd=14 closed (connection lost)
```
Any idea about why this could be?  I have set the following env. variables:
"LDAP_ORGANISATION":"..."
"LDAP_DOMAIN":"..."
"LDAP_ADMIN_PASSWORD":"..."

**Comment by obourdon** [comment]
@vidarkongsli did you had a look at [https://github.com/osixia/docker-openldap/issues/233#issuecomment-409830572](https://github.com/osixia/docker-openldap/issues/233#issuecomment-409830572) ?

**Comment by vidarkongsli** [comment]
@obourdon Thanks for your response. Yes, I did look at that. I am even running with `LDAP_TLS_VERIFY_CLIENT=never` (I also tried `LDAP_TLS_VERIFY_CLIENT=try`) with no luck.

**Comment by obourdon** [comment]
@vidarkongsli could you please try to run the following command on any remote system towards your Azure container instance and give output of the command and logs ?

`openssl s_client -connect test-ldap.uksouth.azurecontainer.io:636`

in my case, without the LDAP_TLS_VERIFY_CLIENT=try the above command exits with failure wheras adding the env flag make it wait for more dataexchange, meaning the TLS exchange was successful

> 5c7648cd conn=1009 fd=12 ACCEPT from IP=172.17.0.1:53398 (IP=0.0.0.0:636)
5c7648cd conn=1009 fd=12 TLS established tls_ssf=256 ssf=256
5c7649bc conn=1009 fd=12 closed (connection lost)


However, whatever the environment I use between docker on Linux, docker on MacOSX or Azure containers I never manage to get the following to return anything

`ldapsearch -ZZ -x -H ldaps://172.17.0.2  -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin`

**Comment by vidarkongsli** [comment]
Thank you for your feedback. 
I downgraded the image version to 1.2.2, and then it works, so it seems to be an issue with version 1.2.3.

**Comment by obourdon** [comment]
@vidarkongsli could you please give all the ENV variables and values you are using for the working 1.2.2 and the command(s) you run to check that it is effectively working

**Comment by vidarkongsli** [comment]
These are my environment variables:
```
LDAP_ADMIN_PASSWORD = "..."
LDAP_DOMAIN = "something.no"
LDAP_ORGANISATION = "..."
LDAP_TLS_VERIFY_CLIENT = never
```
I connect with Apache Directory Studio ("Use SSL Enctyption", port 636)

**Comment by obourdon** [comment]
@vidarkongsli on my side trying 1.2.2 + port 636 never works with Use SSL but does with use startTLS when I click on Check Network parameters

Please note also that ADS has weird non-predictible behaviour on my MacOSX platform, clicking check network parameters several times in a row sometimes succeed sometimes not :-(

Therefore using ldapsearch CLI would definitely be a better option

**Comment by vidarkongsli** [comment]
This now works for me in version 1.2.4

**Comment by schmunk42** [comment]
> This now works for me in version 1.2.4


@vidarkongsli Is *this* meant to be **TLS** or **SSL** or both?

**Comment by vidarkongsli** [comment]
@schmunk42 TLS. I never tried SSL. I have kept the default cipher suite settings.

**Comment by schmunk42** [comment]
Just for reference, if others stumble upon this issue...

```
ldapsearch -d -1 ...
```

gives you much more debug output... in my case the hostname did not match the one from the cert.
