### ISSUE TITLE
Memberof not configured on first boot

### ISSUE THREAD

**Issue by brodkin** [osixia/docker-openldap#29]
I see a LDIF file that configures the memberof overlay on first boot, but the overlay does not seem to actually be working when groups and users are created. Is this a bug or have I missed something in the configuration? I've never configured the overlay myself before so please forgive me if I am misunderstanding.

**Comment by osixia** [comment]
hello,
its looks like a bug indeed :)

i will try to fix that,
thanks

**Comment by baykovr** [comment]
+1 Same issue.

**Comment by baykovr** [comment]
Digging around, it appears referential integrity is missing from the bootstrap ldif configurations.,

**Comment by baykovr** [comment]
Can be manually resolved post installation by adding memberof and referential integrity post install via ldapadd [1]:

https://gist.github.com/baykovr/672c43b118b955171445 

I don't have the time right now but there needs to be an update to the ldif configuration [2]

https://technicalnotes.wordpress.com/2014/04/19/openldap-setup-with-memberof-overlay/

[1] https://github.com/rabits/salt-stack-modules/tree/master/ldap/ldif
[2] `image/service/slapd/assets/config/bootstrap/ldif/`

**Comment by brodkin** [comment]
^^ We ended up doing something similar for our setup. It's not that there's anything wrong with the image that has been created--it's just missing the overlay on first run due to a bug. Thankfully this does not impact the usability of the OpenLDAP server.

**Comment by verdenino** [comment]
+1 Same issue.
