### ISSUE TITLE
tls-enable.ldif syntax is wrong

### ISSUE THREAD

**Issue by wilibox** [osixia/docker-openldap#292]
I was trying to run the container with my own certificates.
After some debugging found, that ldapmodify fails with error (80):

cat /container/service/slapd/assets/config/tls/tls-enable.ldif
dn: cn=config
changetype: modify
replace: olcTLSCipherSuite
olcTLSCipherSuite: SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC
-
replace: olcTLSCACertificateFile
olcTLSCACertificateFile: /container/service/slapd/assets/certs/ca.crt
-
replace: olcTLSCertificateFile
olcTLSCertificateFile: /container/service/slapd/assets/certs/ldap.crt
-
replace: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /container/service/slapd/assets/certs/ldap.key
-
replace: olcTLSDHParamFile
olcTLSDHParamFile: /container/service/slapd/assets/certs/dhparam.pem
-
replace: olcTLSVerifyClient
olcTLSVerifyClient: allow
+ ldapmodify -Y EXTERNAL -Q -H ldapi:/// -f /container/service/slapd/assets/config/tls/tls-enable.ldif
+ log-helper debug
5c6c2ba6 conn=1000 fd=12 ACCEPT from PATH=/var/run/slapd/ldapi (PATH=/var/run/slapd/ldapi)
5c6c2ba6 conn=1000 op=0 BIND dn="" method=163
5c6c2ba6 conn=1000 op=0 BIND authcid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth"
5c6c2ba6 conn=1000 op=0 BIND dn="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" mech=EXTERNAL sasl_ssf=0 ssf=71
5c6c2ba6 conn=1000 op=0 RESULT tag=97 err=0 text=
5c6c2ba6 conn=1000 op=1 MOD dn="cn=config"
5c6c2ba6 conn=1000 op=1 MOD attr=olcTLSCipherSuite olcTLSCACertificateFile olcTLSCertificateFile olcTLSCertificateKeyFile olcTLSDHParamFile olcTLSVerifyClient
5c6c2ba6 conn=1000 op=1 RESULT tag=103 err=80 text=
5c6c2ba6 conn=1000 op=2 UNBIND
5c6c2ba6 conn=1000 fd=12 closed
ldap_modify: Other (e.g., implementation specific) error (80)
modifying entry "cn=config"
*** /container/run/startup/slapd failed with status 80

*** Run commands before finish...
*** Killing all processes...
5c6c2ba6 daemon: shutdown requested and initiated.
5c6c2ba6 slapd shutdown: waiting for 0 operations/tasks to finish
5c6c2ba6 slapd stopped.

Once I added an empty line after `changetype: modify`, ldapmodify ran successfully.

**Comment by wilibox** [comment]
I am closing this issue as the solution I found, does not work.. there is more problems when you try using your own certificates..

**Comment by ilovemysillybanana** [comment]
@wilibox ...so did you ever find a way to fix this? I'm having this issue now

**Comment by obourdon** [comment]
@wilibox @ilovemysillybanana did you have a look at [the TLS documentation link](https://github.com/osixia/docker-openldap/blob/stable/README.md#tls) as well as the [extended example](https://github.com/osixia/docker-openldap/tree/stable/example/extend-osixia-openldap) which also handles this differently

**Comment by wilibox** [comment]
> @wilibox ...so did you ever find a way to fix this? I'm having this issue now

@ilovemysillybanana I had to go with different approach and use other docker image because this one hangs and stops responding until restart in my environment.
