### ISSUE TITLE
When is 1.2.4 going to replace broken 1.2.3?

### ISSUE THREAD

**Issue by jayb1122** [osixia/docker-openldap#296]
https://github.com/osixia/docker-openldap/issues/283

**Comment by therealfarfetchd** [comment]
In the meantime, there's a workaround: set 
`LDAP_BASE_DN='dc=example,dc=com'` for `LDAP_DOMAIN='example.com'`

**Comment by BertrandGouny** [comment]
done :)
sorry guys i was a bit busy on other projects

**Comment by fuxx** [comment]
Everything is fine, don't get stressed by people. You still do it for free :) 
Thanks for the quick release!

**Comment by koelle25** [comment]
@jayb1122 I suspect you can close this issue now.

**Comment by obourdon** [comment]
@jayb1122 please close this issue
