### ISSUE TITLE
starting from old data

### ISSUE THREAD

**Issue by t5unamie** [osixia/docker-openldap#3]
Hi there,

I am starting a container using the following docker run command.

docker run --name openldap -d --restart always -p 389:389 -v /opt/data/ldap/db:/var/lib/ldap -v /opt/data/ldap/config:/etc/ldap/slapd.d -v /opt/data/ldap/ssl/:/osixia/slapd/ssl/ -e LDAP_DOMAIN=example.com -e LDAP_ORGANISATION="example" -e SERVER_NAME="example.com" -e SSL_CRT_FILENAME=ldap.crt -e SSL_KEY_FILENAME=ldap.key -e SSL_CA_CRT_FILENAME=ca.crt osixia/openldap

This command works fine, however if I remove the container. using docker rm -f <ID> and try to the same docker run command above. The following issue occurs.

{code}
*** Killing all processes...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/slapd...
Files /osixia/slapd/ssl/ldap.crt and /osixia/slapd/ssl/ldap.key already exists
ldap_modify: Inappropriate matching (18)
        additional info: modify/add: olcTLSCipherSuite: no equality matching rule
modifying entry "cn=config"

*** /etc/my_init.d/slapd failed with status 18

*** Killing all processes...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/slapd...
Files /osixia/slapd/ssl/ldap.crt and /osixia/slapd/ssl/ldap.key already exists
ldap_modify: Inappropriate matching (18)
        additional info: modify/add: olcTLSCipherSuite: no equality matching rule
modifying entry "cn=config"
{code}

this suggest mounting out the config causes issue during the rebuild of a server using the same configuration on another server,

This seems to differ from the implementation in 0.9.1 where is was possible to simply move a server from one docker server to another as long as you had the data files. 

Regards

John

**Comment by osixia** [comment]
Thanks for reporting this issue the fix will be release soon
