### ISSUE TITLE
readonly user acl can not come info effect

### ISSUE THREAD

**Issue by longwdl** [osixia/docker-openldap#31]
I can not login by user ***readonly*** from phpldapadmin.  
```
Login DN: cn=readonly,dc=example,dc=com
Password: readonly
```

Then I build custom image after change the file ***readonly-user-acl.ldif***. Anonymous login also can not read anything   
```
--- a/image/service/slapd/assets/config/bootstrap/ldif/readonly-user/readonly-user-acl.ldif
+++ b/image/service/slapd/assets/config/bootstrap/ldif/readonly-user/readonly-user-acl.ldif
@@ -4,4 +4,4 @@ delete: olcAccess
 -
 add: olcAccess
 olcAccess: to attrs=userPassword,shadowLastChange by self write by dn="cn=admin,{{ LDAP_BASE_DN }}" write by anonymous auth by * none
-olcAccess: to * by self write by dn="cn=admin,{{ LDAP_BASE_DN }}" write by dn="cn={{ LDAP_READONLY_USER_USERNAME }},{{ LDAP_BASE_DN }}" read by * none
+olcAccess: to * by self write by dn="cn=admin,{{ LDAP_BASE_DN }}" write by dn="cn={{ LDAP_READONLY_USER_USERNAME }},{{ LDAP_BASE_DN }}" read by * read
```

**Comment by osixia** [comment]
Hello,
the readonly user configuration takes place only when a container is started without an existing db and config. 

You do not need to edit readonly-user-acl.ldif file. Just set --env LDAP_READONLY_USER=true to your docker run command:
```
docker run --env LDAP_READONLY_USER=true --detach openldap:1.1.1 
```
and the readonly user will be added when bootstraping the new ldap database.

**Comment by longwdl** [comment]
Thank you, I create a new db then the problem resolved.
