### ISSUE TITLE
Unable to get openldap to work with user-supplied certificates

### ISSUE THREAD

**Issue by siddjain** [osixia/docker-openldap#313]
I am curious if anyone has been able to get this image to work with **user supplied certificates** and could provide the details. For us, it doesn't work. Whenever we try to run using user-supplied certificates, there is error on the client - signature verification failed. Our complete command to run openldap is as follows and we have verified using openssl that our cert is properly signed by our CA. 

```
docker run -p 636:636 \
--name $NAME \
--volume ${PWD}/data/slapd/database:/var/lib/ldap \
--volume ${PWD}/data/slapd/config:/etc/ldap/slapd.d \
--volume ${PWD}/data/slapd/certs:/container/service/slapd/assets/certs \
--env LDAP_TLS_CRT_FILENAME=jnj-ldap-server-tls.pem \
--env LDAP_TLS_KEY_FILENAME=jnj-ldap-server-tls.key \
--env LDAP_TLS_CA_CRT_FILENAME=jnj-ca-chain.pem \
--env LDAP_TLS_VERIFY_CLIENT=never \
--env LDAP_TLS_ENFORCE=true \
--env HOSTNAME=jnj-ldap-server \
--env LDAP_DOMAIN="jnj.com" \
--env LDAP_ADMIN_PASSWORD="superman" \
--env LDAP_LOG_LEVEL:-1 \
--detach osixia/openldap:1.2.4 --loglevel debug --copy-service
```

**Comment by obourdon** [comment]
@siddjain same comment here than [Issue #315](https://github.com/osixia/docker-openldap/issues/315#issuecomment-485812062). Logs and running openssl CLI and giving output might be very helpful
