### ISSUE TITLE
Quick howto is wrong? 

### ISSUE THREAD

**Issue by ronnicek** [osixia/docker-openldap#32]
Hi,

I am testing this image right now and I found one error (maybe I am doing something wrong), but when I run ldapsearch, I get this error:

 `# docker exec -it openldap ldapsearch -x -h localhost -b dc=example,dc=net -D "cn=admin,dc=example,dc=net" -w admin
ldap_bind: Invalid credentials (49)`

But when I run it as this, it works (from host to container):
`ldapsearch -x -h 172.17.0.8 -b dc=example,dc=net -D "cn=admin,dc=example,dc=net" -W admin`

So I think command in howto should looks like this:
`docker exec -it openldap ldapsearch -x -h localhost -b dc=example,dc=net -D "cn=admin,dc=example,dc=net" -W admin`

**Comment by osixia** [comment]
Hi,
the quick start example you take is outdated please take a look to README.md file

Run OpenLDAP docker image:
```
docker run --name my-openldap-container --detach osixia/openldap:1.1.0
```
This start a new container with OpenLDAP running inside. Let's make the first search in our LDAP container:
```
docker exec my-openldap-container ldapsearch -x -h localhost -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin
```

**Comment by ronnicek** [comment]
Ah, I think problem is because I have password for admin user :) and by default there is no password if I not set it in ENV, right?

**Comment by ronnicek** [comment]
Ah, I should use -w myPassword
