### ISSUE TITLE
What is password of billy?

### ISSUE THREAD

**Issue by ibrarahmad** [osixia/docker-openldap#328]

**Comment by obourdon** [comment]
@ibrarahmad I did not find this info anywhere and there is no (easy) way to decode it from the value in the LDIF file.

However, you can set your own password using the following procedure:

```
cd example/extend-osixia-openldap
# Substitute your own password
sed -i -e "s/userPassword:.*/userPassword: $(docker run  --entrypoint=slappasswd osixia/openldap -h {SSHA} -s your-own-password-here)/" bootstrap/ldif/billy.ldif
# rebuild image
make build
# Launch container
docker run --rm --name ldap --detach osixia/extend-osixia-openldap:0.1.0
# Use billy
docker exec -it ldap ldapsearch -x -H ldap://localhost -b "uid=billy,dc=example,dc=org"  -D "uid=billy,dc=example,dc=org" -w your-own-password-here
```

HTH

**Comment by BertrandGouny** [comment]
Hello @obourdon, 
i just would let you know that i see the reply you make on several issue,
and your help is very appreciated, thanks you very much :)

**Comment by obourdon** [comment]
@BertrandGouny you are very welcome

**Comment by obourdon** [comment]
@ibrarahmad If you find the answer helpful, thanks for closing this issue
