### ISSUE TITLE
How to properly setup permissions

### ISSUE THREAD

**Issue by christianvw** [osixia/docker-openldap#343]
Hi,

I am wondering how to setup any permissions for my docker openLDAP server. It is not possible via the phpLdapAdmin webinterface for my understanding.

- How can I disable the anonymous login? What is this even for?
- How can I prevent users from reading anything? They should only see themself and should have the ability to change their password, nothing more.

I've read that you have to do this with ACLs but I don't get the point how to edit the existing rules.

I see some interesting looking files `/etc/ldap/slap.d/` but what is what and how can I edit them persistently? I thought thats the whole point of docker that you can take your `docker-compose.yml` to a different machine and everything works the same way it did before. So executing some commands in the container after creation of this container seems stupid for me?

**Comment by obourdon** [comment]
@christianvw I do not really think this is the place to ask for this kind of questions as they are more related to OpenLDAP itself than the container which "implements" it.

You can also use Google to look for the information you request and you can easily find references like [this link](https://serverfault.com/questions/63916/how-to-disable-anonymous-access-on-ldap) and then see how to make this fits into [the container's own way of initializing.](https://github.com/osixia/docker-openldap/blob/stable/README.md#seed-ldap-database-with-ldif).

Other useful docs can be found in the official OpenLDAP documentation like [this one](https://www.openldap.org/doc/admin24/access-control.html)

HTH

**Comment by christianvw** [comment]
It can be done through a custom ldif-file. Thank you!
