### ISSUE TITLE
How to start replication only

### ISSUE THREAD

**Issue by zhb127** [osixia/docker-openldap#345]
I already have an existing ldap server，Can i only config replication like this：

![image](https://user-images.githubusercontent.com/5210208/62454114-47e2a280-b7a6-11e9-9f54-43a19f5723e0.png)

![image](https://user-images.githubusercontent.com/5210208/62454924-d4da2b80-b7a7-11e9-8a03-b9979d22dd52.png)

![image](https://user-images.githubusercontent.com/5210208/62454407-d820e780-b7a6-11e9-84c4-c78da5088c89.png)

**Comment by 2030405043** [comment]
Hello, how to solve this problem?

**Comment by zhb127** [comment]
I have not practiced it yet.
