### ISSUE TITLE
Update password hashing algorithms

### ISSUE THREAD

**Issue by christianvw** [osixia/docker-openldap#347]
Hi,

is it possible to update the supported hashing algorithms for users passwords?

I only have the following available: `blowfish`, `crypt`, `ext_des`, `md5`, `k5key`, `md5crypt`, `sha`, `smd5`, `ssha`, `sha512`, `sha256crypt`, `sha512crypt`

All I read online regarding this algorithms, is that these are simply outdated and you should use `bcrypt` instead.

**Comment by fargusplumdoodle** [comment]
I also think it would be a good idea to store passwords with Argon2.

https://en.wikipedia.org/wiki/Argon2

Is there any plan on updating this? Im struggling to get JNDI to store passwords in anything other than plain text.

**Comment by tulir** [comment]
It seems like Argon2 is now supported in some way. `slapd-contrib` v2.4.50 added an Argon2 module (`pw-argon2`) and this image installs that version from buster-backports. I'm not sure how to configure this to use argon2 though.

**Comment by christianvw** [comment]
Yes, Argon2 now seems to be supported in OpenLDAP 2.4.50 But I couldn't get Argon2 to work with the Docker image. I tried to set the password manually according to the scheme:

````
{ARGON2}...
````

But it did not work. It failed to validate the hashes with the entered password.

Also creating a hash in the OpenLDAP container using `slappasswd` did not work and the error message appeared that the scheme (Argon2) was not supported.

**Comment by tulir** [comment]
The module needs to be loaded explicitly: `slappasswd -o module-load=pw-argon2 -h {ARGON2}`.

To load the module in the daemon:

```ldif
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: {0}pw-argon2
```

and then to configure it to use Argon2:

```ldif
dn: olcDatabase={-1}frontend,cn=config
changetype: modify
add: olcPasswordHash
olcPasswordHash: {ARGON2}
```

**Comment by christianvw** [comment]
Thank you very much @tulir that worked perfectly!

I was able to add your lines to my default LDIF file, which goes into the container by volume.

**custom.ldif**
````
#other things like disabling anon bind
#...


#load argon2 module and configure it to load it

dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: {0}pw-argon2

dn: olcDatabase={-1}frontend,cn=config
changetype: modify
add: olcPasswordHash
olcPasswordHash: {ARGON2}
````

**docker-compose.yml**
````
volumes:
    # persistent storage...
    - ./custom.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/custom.ldif
````

PhpLDAPadmin does not support Argon2 yet, but that is a different topic.

**Comment by trallnag** [comment]
Hey @christianvw, did you execute anything before applying the LIDF? It doesn't work for me...

![image](https://user-images.githubusercontent.com/24834206/124400189-f55ae980-dd20-11eb-8fce-596f388e615d.png)
![image](https://user-images.githubusercontent.com/24834206/124400199-fdb32480-dd20-11eb-996e-45fdd6cc5ac7.png)

**Comment by trallnag** [comment]
Okay seems like my problem has nothing to do with the argon module but cn=module. I'm logged in as admin

**Comment by trallnag** [comment]
@christianvw, how to you create new passwords without phpLDAPadmin supporting it?

**Comment by trallnag** [comment]
```
slappasswd -h '{SHA512}' -o module-load=pw-sha2
```

**Comment by trallnag** [comment]
If anyone is curious on how to tweak parameters check this mail chain:

https://www.mail-archive.com/search?l=openldap-bugs@openldap.org&q=subject:%22%5C%5BIssue+9517%5C%5D+Documenting+how+to+pass+Argon2+configuration+parameters+when+loading+the+module%22&o=newest&f=1
