### ISSUE TITLE
slapd tcp bind is network not interface, and so does not respond on overlay networks

### ISSUE THREAD

**Issue by MattParr** [osixia/docker-openldap#35]
I am using an rancher for docker orchestration.  It adds an overlay network... an alias IP on the docker network interface.  http://docs.rancher.com/rancher/concepts/#networking

The issue is that the service startup binds to specific IP addresses, and is not listening on the overlay IP address

the process is started:
```
exec /usr/sbin/slapd -h "ldap://$HOSTNAME ldaps://$HOSTNAME ldap://localhost ldaps://localhost ldapi:///" -u openldap -g openldap -d $LDAP_LOG_LEVEL
```
which gives me:
```
root@ldap_1:/# netstat -nlp                                           
Active Internet connections (only servers)                                      
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
PID/Program name                                                                
tcp        0      0 127.0.0.1:636           0.0.0.0:*               LISTEN      
tcp        0      0 172.17.0.5:636          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:389           0.0.0.0:*               LISTEN      
tcp        0      0 172.17.0.5:389          0.0.0.0:*               LISTEN      
tcp6       0      0 ::1:636                 :::*                    LISTEN      
tcp6       0      0 ::1:389                 :::*                    LISTEN      
```
I have the following addresses on the docker interface:
```
root@ldap_1:/# ip addr show dev eth0                                  
40: eth0@if41: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
 group default                                                                  
    link/ether 02:95:3f:7b:35:1c brd ff:ff:ff:ff:ff:ff                          
    inet 172.17.0.5/16 scope global eth0                                        
       valid_lft forever preferred_lft forever                                  
    inet 10.42.144.192/16 scope global eth0                                     
       valid_lft forever preferred_lft forever                                  
    inet6 fe80::95:3fff:fe7b:351c/64 scope link                                 
       valid_lft forever preferred_lft forever
```
The LDAP service does not respond on 10.42.144.192, but it does respond on 172.17.0.5.

**Comment by SerialVelocity** [comment]
I'm encountering the same issue, did you find a fix/workaround?

**Comment by tlchan** [comment]
I have not used rancher but have you tried specifying the overlay IP rather than the hostname? 

```
exec /usr/sbin/slapd -h "ldap://$HOSTNAME ldaps://$HOSTNAME 
```

**Comment by SerialVelocity** [comment]
You mean putting the IP in the hostname variable? Doesn't really work like that as the IP changes when upgrades occur and probably everytime the server is restarted (not sure on the second bit)

**Comment by osixia** [comment]
Hi,
is there a way to get the ip you should listen on in the container ?

**Comment by SerialVelocity** [comment]
I guess by parsing the ip list from ipconfig or something. I don't understand why openldap isn't just listening to every ip available with "ldap://". It's inside a docker container.

**Comment by osixia** [comment]
A hostname must be set for the replication, that's why it listen on ldap://$HOSTNAME

**Comment by SerialVelocity** [comment]
Is it possible to listen on ldap:// and ldap://$HOSTNAME? Or make it possible to listen on ldap:// when replication is disabled?

**Comment by osixia** [comment]
It's not possible to listen on ldap:// and ldap://$HOSTNAME.
Does rancher add in the container any environment variable to get the other ip ? Set any /etc/hosts entry... ?

**Comment by osixia** [comment]
Hello,
v1.1.2 should fix this issue can you confirm ?
