### ISSUE TITLE
overlays and copy-service: order of operation

### ISSUE THREAD

**Issue by DemianTinkiel** [osixia/docker-openldap#352]
Hi.

I'm loading seed data into LDAP via 
```
 command: --copy-service
    volumes:
      - ./ldap/seed:/container/service/slapd/assets/config/bootstrap/ldif/custom
```

where `./ldap/seed` contains a db.ldif file with

```
#################################################### Groups ############################################################
dn: cn=admin,dc=mycomp,dc=com
cn: admin
uniquemember: cn=alice,dc=mycomp,dc=com
objectclass: groupOfUniqueNames
objectclass: top

#################################################### Users #############################################################
dn: cn=alice,dc=mycomp,dc=com
cn: alice
objectclass: person
objectclass: top
sn: testuser
```
The thing is that if I initially do
```
ldapsearch -LLL -x -D cn=admin,dc=example,dc=org -w admin -b dc=example,dc=org -h 127.0.0.1 cn=alice memberOf
```
`memberOf` does not appear as part of the result

but if I delete the group and import it again and repeat the command, then the operational attribute `memberOf` appears as part of the result

So the question is are modules added before custom assets?
or maybe this is related to the order of loading `03-memberOf.ldif` vs my file (db.ldif)?

I thought this question was related to #304 or  #49  but in this case `memberOf` does work, just not immediately upon starting my compose

**Comment by obourdon** [comment]
@DemianTinkiel as per [this line in the startup code](https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/startup.sh#L308) and [this other line](https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/startup.sh#L324) custom assets are the very last items which get added to your LDAP configuration.

You can also make sure of this by adding the ```--loglevel debug``` parameters to your ```--copy-service```

What is strange from the ldif file you provide above is the fact that objects defined in it do not belong to dc=example,dc=org like your ldap_search bind DN and base suggest.

You may also want to have a look at other issues like [#304](https://github.com/osixia/docker-openldap/issues/304) which are also related to memberOf

**Comment by DemianTinkiel** [comment]
@obourdon thanks for that. It seems the order of operation in the ldif file is important. Defining the user first and then the user seems to have solved the problem
