### ISSUE TITLE
The old password can still be logged in after changing the password

### ISSUE THREAD

**Issue by happinesslijian** [osixia/docker-openldap#356]
When I change the default cn=admin password, the old password "admin" can still be logged in. The new password can also be logged in. This is not logical, please give the correct instructions.
```
image: osixia/openldap:1.2.5
```

**Comment by BertrandGouny** [comment]
is this related to #161 ?

**Comment by happinesslijian** [comment]
Yes, it is, what does it mean that both old and new passwords can be logged in is normal?
