### ISSUE TITLE
Release Date v1.3.0

### ISSUE THREAD

**Issue by FloV22** [osixia/docker-openldap#357]
I saw that you are currently working on a new release which includes the new version of openldap (**2.4.48**) and i want to know if you have a release date of this new version ?

Otherwise are you using the last patched version of openldap ?

**Comment by BertrandGouny** [comment]
Hello,
1.3.0 try to be multi-arch release but tests are not ok on other arch than amd64.
After that it will be released ASAP.

Any help welcome :)

**Comment by obourdon** [comment]
@FloV22 1.3.0 has been officially available for some time now. Thanks for closing this issue
