### ISSUE TITLE
Can't use base_dn with spaces

### ISSUE THREAD

**Issue by yesennes** [osixia/docker-openldap#366]
I'm trying to use this for a organization with a space in its name.

When I run it like so:

```
docker run -p 389:389 -p 636:636 --env LDAP_BASE_DN="O=a b, C=c" --env LDAP_DOMAIN="a b.c" --name my-openldap-container  osixia/openldap:1.3.0 --loglevel debug
```

It just hangs after "Init new ldap server...". I'm pretty sure this is a valid name for a ldap organization, but even if it isn't some error message instead of hanging would be nice.

Thanks

**Comment by obourdon** [comment]
@yesennes indeed this would be nice

However, further digging into your issue showed that this was not an issue in osixia/openldap Docker container but more a "generic" Debian 10 issue

By setting a set -x instruction [after the following line](https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/startup.sh#L137) it appears that the hang occurs in the call to [dpkg-reconfigure -f noninteractive slapd](https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/startup.sh#L155)

Seems more like a generic debian issue really

**Comment by obourdon** [comment]
Just as a complement, I tried to supply values with spaces when installing OpenLDAP on Debian Buster from scratch (meaning not using any part of osixia/openldap) and it keep telling me that the configuration is invalid. So may be spaces are allowed in LDAP as a whole but may be there are some other adherences due to distributions/installation scripts specificities...

**Comment by obourdon** [comment]
@yesennes seems like some other people do not like/trust the way debian is initializing/configuring OpenLDAP: see [this item in another issue](https://github.com/osixia/docker-openldap/issues/342#issuecomment-542586248) I submitted some time ago.
