### ISSUE TITLE
LDAP Number of Threads

### ISSUE THREAD

**Issue by rg2609** [osixia/docker-openldap#368]
What is the Maximum Number of Threads in LDAP, and what is the default number of Threads.

**Comment by obourdon** [comment]
@rg2609 please note that this repository is aimed at one of the OpenLDAP Docker containers
General questions should be asked on all medias mentioned on openldap.org

Googling a little bit give stuff like [this link](https://www.openldap.org/faq/data/cache/1129.html)

Looking within a running osixia/openldap container shows:
```
root@9d7986777d3a:/# grep -i thre /proc/494/status
Threads:	3
root@9d7986777d3a:/# ps -hH 494 | wc -l
3
```

on my MacOSX Docker runtime

It seems that this can be tuned as explained in this [slapd.conf manual page](https://aput.net/~jheiss/krbldap/files/slapd.conf)

**Comment by quanah** [comment]
For a URL, I'd use this one for [slapd.conf](https://www.openldap.org/software/man.cgi?query=slapd.conf&apropos=0&sektion=0&manpath=OpenLDAP+2.4-Release&format=html)

I would note that depending on the CPU resources available, more threads can lead to worse performance, not better.

**Comment by rg2609** [comment]
closing
