### ISSUE TITLE
specify base_dn without domain

### ISSUE THREAD

**Issue by mizunashi-mana** [osixia/docker-openldap#37]
I want to specify `LDAP_BASE_DN` without `LDAP_DOMAIN`.

Now, this startup script set `LDAP_BASE_DN` using `get_ldap_base_dn`(ref: https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/startup.sh#L164).

This function convert `LDAP_DOMAIN` to `LDAP_BASE_DN`.  This is useful, but, I want to specify `LDAP_BASE_DN` and `LDAP_DOMAIN` separately.

I think `LDAP_BASE_DN` should be added in public environment values, and if the env has no value, be set converted `LDAP_DOMAIN`.

What about it?

**Comment by osixia** [comment]
good idea :)
