### ISSUE TITLE
 When running on CircleCI: bind(8) failed errno=99 (Cannot assign requested address)

### ISSUE THREAD

**Issue by PeterJCLaw** [osixia/docker-openldap#373]
This is similar to #218, #198 and #129; I'm happy for this to be closed as duplicate against on of those if that's preferred.

I'm trying to use this docker image as part of a CircleCI config to test an LDAP client application. I've actually got a [derived Docker image](https://github.com/PeterJCLaw/sr-ldap-docker) which customises the actual database a bit, though the issue I'm hitting happens before the database actually gets going and reproduces with a the latest `osixia/openldap` image (without customisations).

Running with `--loglevel debug` yields the following log lines (from https://circleci.com/gh/PeterJCLaw/libnemesis/28):
```
...
Database and config directory are empty...
Init new ldap server...
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.48+dfsg-1~bpo10+1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Start OpenLDAP...
Waiting for OpenLDAP to start...
5dd07194 @(#) $OpenLDAP: slapd  (Jul 30 2019 16:24:19) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5dd07194 daemon: bind(9) failed errno=99 (Cannot assign requested address)
5dd07194 slapd starting
5dd07194 daemon: listen(ldap://localhost, 5) failed errno=98 (Address already in use)
5dd07194 slapd stopped.
```

Any ideas on how to fix this?

**Comment by PeterJCLaw** [comment]
I've found a fix for this -- by setting the [`name`](https://circleci.com/docs/2.0/configuration-reference/#docker) of the `executor` the container is then able to start up cleanly.
I'm not sure what that maps to for other Docker environments, but thought it worth sharing as a solution to this case.

**Comment by thche** [comment]
@PeterJCLaw nice! thanks for that one!
