### ISSUE TITLE
where can i find executable files like ldapsearch, ldapadd and all?

### ISSUE THREAD

**Issue by pasumarthivijaykumar** [osixia/docker-openldap#375]
where can i find executable files like ldapsearch, ldapadd and all?
please share me info.
as in image i wanted location of executable files ldapsearch, ldapadd and all?

**Comment by obourdon** [comment]
@pasumarthivijaykumar not sure what you are really asking for here

On your host, it depends of the OS you are using of course. On MacOSX for instance you can use MacPorts or Homebrew to install openldap-clients/utilities and then find them in /opt/local/bin or /usr/local/bin. On Linux this is pretty much standard (distro dependant though).

On Windows, just google for 'ldapsearch windows' and you should be able to find something worth trying.

In the container, as it is based on Debian 10 (buster) they are in your path by default: /usr/bin/ldapsearch ...
HTH

**Comment by pasumarthivijaykumar** [comment]
Thanks a lot for the quick help. I am very much bothered to search each thing (schema, ldifs, bins) in very different locations, compared to normal openldap file system.
