### ISSUE TITLE
where can i find, mdb directory in file system

### ISSUE THREAD

**Issue by pasumarthivijaykumar** [osixia/docker-openldap#376]
As per the details mentioned **"By default this image is waiting an mdb database backend,**"
can you please let us know where mdb directory location ?
or you wanted us create the directory while configuration of mdb.?

**Comment by obourdon** [comment]
@pasumarthivijaykumar I am not an expert in this config area of OpenLDAP/osixia but seems to be that it should be ```/var/lib/ldap/data.mdb``` no ?

**Comment by pasumarthivijaykumar** [comment]
yes, thank you.
