### ISSUE TITLE
when i load database config, i see two files of mdb.ldif, which one will be used for actual user content to storeto

### ISSUE THREAD

**Issue by pasumarthivijaykumar** [osixia/docker-openldap#378]
Hi,

When a create a container, i see 'olcDatabase={1}mdb.ldif' at /etc/ldap/slapd.d/cn=config
when a load my db configuration using below command there is another db file generated as 'olcDatabase={2}mdb.ldif'

root@x:/etc/ldap/slapd.d/cn=config# ls -lrt
total 36
-rw------- 1 openldap openldap  657 Nov 22 08:59 'olcDatabase={-1}frontend.ldif'
-rw------- 1 openldap openldap  414 Nov 22 08:59 'olcBackend={0}mdb.ldif'
-rw------- 1 openldap openldap  396 Nov 22 08:59 'cn=schema.ldif'
-rw------- 1 openldap openldap  654 Nov 22 08:59 'olcDatabase={0}config.ldif'
drwxr-x--- 2 openldap openldap 4096 Nov 22 08:59 'olcDatabase={1}mdb'
-rw------- 1 openldap openldap  543 Nov 22 08:59 'cn=module{0}.ldif'
-rw------- 1 openldap openldap 1070 Nov 22 08:59 **'olcDatabase={1}mdb.ldif'**
drwxr-x--- 2 openldap openldap 4096 Nov 22 09:07 'cn=schema'
-rw------- 1 openldap openldap  768 Nov 22 09:07 **'olcDatabase={2}mdb.ldif'**

above two files configuration values are different (ex: dir value), which file will be picked for user ldap data to store?

**Command used to load db config:**
_/usr/bin/ldapadd -x -H ldapi:/// -D "cn=admin,cn=config" -w config -f mdbconfig.ldif_

**Comment by obourdon** [comment]
Not sure what you are asking for/trying to achieve but may be you should have a look at [this section of the readme](https://github.com/osixia/docker-openldap#seed-ldap-database-with-ldif)

Concerning order or loading, considering [this kind of line](https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/startup.sh#L308) in the startup script, items will be sorted by alphabetical order
HTH

**Comment by pasumarthivijaykumar** [comment]
Thanks for the info, i am trying to understand how data is loaded accordingly when i have two configured locations. ex: dbDirectory location for each file.
