### ISSUE TITLE
Run error: docker: Error response from daemon: No command specified.

### ISSUE THREAD

**Issue by akamalov** [osixia/docker-openldap#386]
**Environment:**

```
MacOS X: Mojave
Docker: 19.03.5
docker-openldap: 1.3.0
```
**Running container:**

```
docker run -p 389:389 -p 636:636 --name my-openldap-container --detach osixia/openldap:1.3.0
docker: Error response from daemon: No command specified.
See 'docker run --help'.

```

Looking at Dockerfile of the project, I couldn't find ```ENTRYPOINT``` either.

Thanks!!

Alex

**Comment by akamalov** [comment]
I had to repull. Problem was on my local container image

**Comment by radhikasheladia** [comment]
Add sh or bash at the end of the command 

docker run -p 389:389 -p 636:636 --name my-openldap-container --detach osixia/openldap:1.3.0 sh 

It worked for me
