### ISSUE TITLE
Connection Close issue while for long data load in ldap

### ISSUE THREAD

**Issue by pasumarthivijaykumar** [osixia/docker-openldap#389]
We are getting an OpenLDAP connection lose issue when we try to load / store large amount data (more than 35k characters of string format) . Please use below mentioned connection management logs details,

Logs from LDAP logger level Connection Management:
5df4c06f conn=1022 op=2457 SEARCH RESULT tag=101 err=32 nentries=0 text=
5df4c06f conn=1022 op=2458 ADD dn="cn=com_cordys_cws_runtime_types_teamdevelopment_SCMAdapter.SCMAdapterBinding,cn=Cordys CWS Bootstrap Helper,cn=cordys,cn=defaultInst,o=trialorg.local"
5df4c06f conn=1022 op=2458 RESULT tag=105 err=0 text=
5df4c06f conn=1022 op=2459 SRCH base="cn=determineIncorporateChangeSet,cn=defaultInst,o=trialorg.local" scope=0 deref=0 filter="(objectClass=*)"
5df4c06f conn=1022 op=2459 SRCH attr=* entryUUID
5df4c06f conn=1022 op=2459 SEARCH RESULT tag=101 err=32 nentries=0 text=
5df4c06f conn=1022 fd=18 closed (connection lost)

Log details from Client Application:
<log4j:throwable><![CDATA[LDAPException: Connection lost waiting for results from docker_container.local:636 (91) Connect Error
java.io.EOFException: BERDecoder: decode: EOF in Identifier
        at com.novell.ldap.Connection$ReaderThread.run(Connection.java:1381)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: BERDecoder: decode: EOF in Identifier
        at com.novell.ldap.asn1.ASN1Identifier.<init>(ASN1Identifier.java:132)
        at com.novell.ldap.Connection$ReaderThread.run(Connection.java:1269)
        ... 1 more
]]></log4j:throwable>

can any one please let me know.

**Comment by obourdon** [comment]
@pasumarthivijaykumar not sure what you really meant by load/store but I have interpreted it as you are inserting 35k of data into LDAP using ldapadd or something like it

However, err=32 means 'No such object' which means that you potentially have some errors in the data you are trying to feed into LDAP and may be because of this error, your uploading client cuts the connection and therefore the server part gets 'connection lost'.

My 2 cents

**Comment by pasumarthivijaykumar** [comment]
@obourdon thanks for the details. Apparently, the issue is CipherSuite which is mentioned in https://github.com/osixia/docker-openldap/blob/stable/example/docker-compose.yml
The ciphersuite is not enough for real world scenarios.

When i used default ciphersuite from openLDAP, everything is fine.
