### ISSUE TITLE
Container takes a long time to start

### ISSUE THREAD

**Issue by adhawkins** [osixia/docker-openldap#407]
Trying to get this container up and running using docker-compose. This is the file:

`---
version: "3.5"

networks:
  default:
    name: ldap

services:
  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="My Org"
      - LDAP_DOMAIN="myorg.com"
      - LDAP_READONLY_USER=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./openldap/lib:/var/lib/ldap
      - ./openldap/etc:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636
    restart: unless-stopped
`

It's been running the `dpkg-reconfigure` bit for well over an hour now. There's no evidence of any files being created in the mounts for `/var/lib/ldap` and `/etc/ldap/slapd.d`. How long should this take?

**Comment by adhawkins** [comment]
And still running two days later. Something amiss. Suggestions appreciate.

Log:

`openldap    | *** CONTAINER_LOG_LEVEL = 3 (info)
openldap    | *** Search service in CONTAINER_SERVICE_DIR = /container/service :
openldap    | *** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
openldap    | *** link /container/service/slapd/startup.sh to /container/run/startup/slapd
openldap    | *** link /container/service/slapd/process.sh to /container/run/process/slapd/run
openldap    | *** Set environment for startup files
openldap    | *** Environment files will be proccessed in this order :
openldap    | Caution: previously defined variables will not be overriden.
openldap    | /container/environment/99-default/default.yaml
openldap    | /container/environment/99-default/default.startup.yaml
openldap    |
openldap    | To see how this files are processed and environment variables values,
openldap    | run this container with '--loglevel debug'
openldap    | *** Running /container/run/startup/:ssl-tools...
openldap    | *** Running /container/run/startup/slapd...
openldap    | Database and config directory are empty...
openldap    | Init new ldap server...
`

Docker-compose file:

`---
version: "3.5"

networks:
  default:
    name: ldap

services:
  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="Cabletime Limited"
      - LDAP_DOMAIN="cabletime-ldap.com"
      - LDAP_READONLY_USER=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./openldap/lib:/var/lib/ldap
      - ./openldap/etc:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636
    restart: unless-stopped
`

**Comment by obourdon** [comment]
@adhawkins searching for [issues similar to yours](https://github.com/osixia/docker-openldap/search?q=dpkg-reconfigure&type=Issues) might have helped you in the first place and namingly [this one](https://github.com/osixia/docker-openldap/issues/366)

Are you sure there are no spurious spaces in the environment variables contents above ???

On my side, running
```
$ docker run -e LDAP_ORGANISATION="My Org" -e LDAP_DOMAIN=" myorg.com" -e LDAP_READONLY_USER=true -e PUID=1000 -e PGID=1000 -e TZ=Europe/London osixia/openldap:1.3.0

*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Database and config directory are empty...
Init new ldap server...
```

gets stuck there in `dpkg-reconfigure` while:

```
$ docker run -e LDAP_ORGANISATION="My Org" -e LDAP_DOMAIN="myorg.com" -e LDAP_READONLY_USER=true -e PUID=1000 -e PGID=1000 -e TZ=Europe/London osixia/openldap:1.3.0
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Database and config directory are empty...
Init new ldap server...
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.48+dfsg-1~bpo10+1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add bootstrap schemas...
config file testing succeeded
Add image bootstrap ldif...
Add read only user...
Add custom bootstrap ldif...
Add TLS config...
No certificate file and certificate key provided, generate:
/container/service/slapd/assets/certs/ldap.crt and /container/service/slapd/assets/certs/ldap.key
2020/03/10 09:15:14 [INFO] generate received request
2020/03/10 09:15:14 [INFO] received CSR
2020/03/10 09:15:14 [INFO] generating key: ecdsa-384
2020/03/10 09:15:14 [INFO] encoded CSR
2020/03/10 09:15:14 [INFO] signed certificate with serial number 512685722477322909843224363253746526620674580811
Link /container/service/:ssl-tools/assets/default-ca/default-ca.pem to /container/service/slapd/assets/certs/ca.crt
Disable replication config...
Stop OpenLDAP...
Configure ldap client TLS configuration...
Remove config files...
First start is done...
*** Set environment for container process
*** Remove file /container/environment/99-default/default.startup.yaml
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/process/slapd/run...
5e675aa3 @(#) $OpenLDAP: slapd  (Jul 30 2019 16:24:19) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5e675aa3 slapd starting
```

just works fine. 

Note that the only difference between the 2 runs is the leading space in `-e LDAP_DOMAIN="myorg.com"`

HTH

**Comment by adhawkins** [comment]
I posted my docker-compose file at the start, as you can see it has no spaces in the value for LDAP_DOMAIN.

However, that did give me the pointer I needed. It appears that quoting the environment variables in the docker-compose file was not the correct thing to do.

Removing the quotes around LDAP_ORGANISATION and LDAP_DOMAIN has got the container started correctly.

Thanks for the assistance @obourdon

**Comment by publicvirtualvoid** [comment]
This report just saved me. 
Is this expected behaviour?
