### ISSUE TITLE
Password are stored in clear

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#418]
By default, password are stored in clear in the latest docker image of [`osixia/openldap:1.3.0`](https://hub.docker.com/r/osixia/openldap).

This is the [`Dockerfile`](https://github.com/osixia/docker-openldap/blob/stable/image/Dockerfile).

I would like to know how I can have encrypted passwords stored in the LDAP with a minimum of:

- modification  (if possible without building a docker image)
- manual edition after deployment  (if possible being able to just remove the container and it's data quickly and starts a new one)

Currently, this is how I start the container:

```python
docker run \
  --cpu-shares 204 \
  --memory 536870912 \
  -e LDAP_ADMIN_PASSWORD=stagingadminpassword \
  -e LDAP_CONFIG_PASSWORD=stagingpassword \
  -e LDAP_DOMAIN=staging-org.com \
  -e LDAP_ORGANISATION=staging-org \
  -v /srv/staging-openldap/var/lib/ldap:/var/lib/ldap:rw \
  -v /srv/staging-openldap/etc/ldap/slapd.d:/etc/ldap/slapd.d:rw \
  --net bridge \
  -p 31753:389/tcp \
  osixia/openldap:1.3.0

```

It's just so it can be used for a production case.

## Related issues

- #418
- #405 
- #351
- #48 
- https://stackoverflow.com/questions/61380279

Thanks a lot.

**Comment by BertrandGouny** [comment]
Hi,
passwords are not stored in clear text in openldap database. It may be stored in clear text in the container if you set it in the environment variable.

To not keep password in clear in environment variable you can use kubernetes init container feature or a job: 
that run a container with all environments variables you want and with password in clear text with argument `-p` to not run process. 
```
args: ["-p"]
```
Take care to set ldap database and config in a volume.

then run a regular container with environment variable **"KEEP_EXISTING_CONFIG"** set to **true** that reuse the same database and config volumes

**Comment by kopax** [comment]
My bad, the password is stored by `SHA1`.

It seems that `spring-security-ldap` is not using `ldap-passwd` which cause the password stored in password field to be in clear text.

It's my bad and thanks for your time.
