### ISSUE TITLE
TLS negotiation failure after disabling TLS

### ISSUE THREAD

**Issue by ChocolateFactory28** [osixia/docker-openldap#42]
I am trying to connect an application with the ldap server based on image oxisia/docker-openldap 1.1.2 . My application uses SSL 3.0, and the ldap server is TLS. So it was giving me TLS Issue: Could not negotiate a supported cipher suite. However, I disabled the TLS with the steps you mentioned in #17 
But now when I run my application with the server, it complains (TLS negotiation failure). 

 
[logs.txt](https://github.com/osixia/docker-openldap/files/194376/logs.txt)

Kindly help

**Comment by osixia** [comment]
Hi,
the container was started without -h option that set the container hostname, so your certificates have been generated with the random container hostname set by docker here : 9b6600e483c6

When you use TLS the client check the server hostname (CN) in the certificate so if you try to connect to ldap.example.org and the ldap server certificat CN is set to 9b6600e483c6 the TLS negociation failed.
