### ISSUE TITLE
Restarting container with new environment

### ISSUE THREAD

**Issue by amsdard** [osixia/docker-openldap#44]
I have problem with restarting container with new environment variables. As I understand during first run, some initialization is done which is not repeated in next runs. This makes me wonder how to normally restart container with new variables like log level? Right now I have to remove container and create it again due to the fact that slapd.d config files are persisted in volume which is reused during restarts.

Beacuse config files are persisted, when I change ie log level it results in error:

> openldap_1     | Start OpenLDAP...
> openldap_1     | Waiting for OpenLDAP to start...
> openldap_1     | 570e7088 @(#) $OpenLDAP: slapd  (Jan 16 2016 23:00:08) $
> openldap_1     | 	root@chimera:/tmp/buildd/openldap-2.4.40+dfsg/debian/build/servers/slapd
> openldap_1     | 570e7088 ldif_read_file: checksum error on "/etc/ldap/slapd.d/cn=config.ldif"
> openldap_1     | 570e7088 <= str2entry NULL (smr_normalize createTimestamp 21)
> openldap_1     | 570e7088 slapd stopped.
> openldap_1     | 570e7088 connections_destroy: nothing to destroy.

I'm running 1.1.2 version and to be clear I've never modified config files manually but added my custom ldifs to /container/service/slapd/assets/config/bootstrap/ldif 

Btw, big thanks for great image!

**Comment by ttsz** [comment]
We have the same issue. 

We set 2 volumes for the container. If we stop the container and  remove it, the datas are still there. When we create a new container using the same volumes and if we ran the container immediately exit. We found the following logs.

Start OpenLDAP...
Waiting for OpenLDAP to start...
57974f8e @ $OpenLDAP: slapd  (Jan 16 2016 23:00:08) $
root@chimera:/tmp/buildd/openldap-2.4.40+dfsg/debian/build/servers/slapd
57974f8e ldif_read_file: checksum error on "/etc/ldap/slapd.d/cn=config.ldif"
57974f8e <= str2entry NULL (smr_normalize createTimestamp 21)
57974f8e slapd stopped.

These are the exposed volumes:
volumes:
      - ~/ldap/database:/var/lib/ldap
      - ~/ldap/config:/etc/ldap/slapd.d

What should be the problem?

Thanks in advance.

**Comment by pvcnt** [comment]
Hello,

The same here, if I start the container with named volumes for data and config, stop and remove it and try to recreate it attached to the same volumes. It never starts.

I have a somewhat different error. Thanks!

```
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:cfssl/startup.sh to /container/run/startup/:cfssl
*** failed to link /container/service/:cfssl/startup.sh to /container/run/startup/:cfssl: [Errno 17] File exists
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** failed to link /container/service/slapd/startup.sh to /container/run/startup/slapd: [Errno 17] File exists
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** directory /container/run/process/slapd already exists
*** failed to link /container/service/slapd/process.sh to /container/run/process/slapd/run : [Errno 17] File exists
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml.startup
/container/environment/99-default/default.yaml
```

**Comment by osixia** [comment]
@pvcnt your error seems different can you please provide the volume mounted ?

**Comment by pvcnt** [comment]
I launch the container with:   `--volume ops-ldap-data:/var/lib/ldap --volume ops-ldap-config:/etc/ldap/slapd.d`

**Comment by pvcnt** [comment]
Ok, sorry, these are some (strange?) errors. But if I start the container with `--loglevel debug` (with previously used volumes) I have the same errors than above.

```
Start OpenLDAP...
Waiting for OpenLDAP to start...
579f8d4d @(#) $OpenLDAP: slapd  (Jan 16 2016 23:00:08) $
	root@chimera:/tmp/buildd/openldap-2.4.40+dfsg/debian/build/servers/slapd
579f8d4d ldif_read_file: checksum error on "/etc/ldap/slapd.d/cn=config.ldif"
579f8d4d <= str2entry NULL (smr_normalize createTimestamp 21)
579f8d4d slapd stopped.
579f8d4d connections_destroy: nothing to destroy.
```

**Comment by phlegx** [comment]
I have the same problems. It seems that the file ```cn\=config.ldif``` looks at some point like this (I have no clue why):

```# AUTO-GENERATED FILE - DO NOT EDIT!! Use ldapmodify.
# CRC32 f0b60ab4
dn: cn=config
objectClass: olcGlobal
cn: config
olcArgsFile: /var/run/slapd/slapd.args
olcLogLevel: none
olcPidFile: /var/run/slapd/slapd.pid
olcToolThreads: 1
structuralObjectClass: olcGlobal
entryUUID: e4a8c6cc-d317-1035-9744-8b74d7246e64
creatorsName: cn=config
createTimestamp: 20160630140841Z
 _bundle
 rivate.key
entryCSN: 20160630141647.856558Z#000000#000#000000
modifiersName: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
modifyTimestamp: 20160630141647Z
```

When I remove the orphaned values ```bundle``` and ```rivate.key``` then it just starts up normally again.
