### ISSUE TITLE
Error on Startup 

### ISSUE THREAD

**Issue by docfactory37** [osixia/docker-openldap#446]
Hi,

Im have just set up the stable container ass per the instruction and im getting the below error on start up.

Hoping you can help 

![image](https://user-images.githubusercontent.com/20963053/87506915-c979ca80-c6af-11ea-92f3-7aee6c930098.png)

**Comment by obourdon** [comment]
@docfactory37 as the error message says, seems there is something already listening on port 389 in your container
Could you please give more information about:
1- which kind of host/OS and version are you running docker on (Linux, Windows, MacOSX)
2- which version of docker (output of `docker version` and `docker info` would be nice)
3- what other containers are running (output of `docker ps`)
3- what does `as per the instruction` means. Please paste your launch command and full trace
thanks

**Comment by obourdon** [comment]
Just searching for `Address already in use` and `errno=98` in this repository you might find some other interesting informations in these links:

-  [Issue #252](https://github.com/osixia/docker-openldap/issues/252)
-  [Issue #198](https://github.com/osixia/docker-openldap/issues/198)
-  [PR #3738](https://github.com/owncloud/phoenix/pull/3738)

**Comment by obourdon** [comment]
@mbasri what is your own error case for this please ?

**Comment by mbasri** [comment]
Hello, I get exactly the same error as @docfactory37,I just updated the version from v 1.3.0 to v 1.4.0, I use LDAPS with a custom `crt` file.

My DockerFile ==>

```
# Sources: https://github.com/osixia/docker-openldap-backup
FROM osixia/openldap-backup:1.3.0
LABEL MAINTAINER="TOTO <toto@toto.com>"

ENV HOSTNAME="openldap.toto.com"
ENV LDAP_ORGANISATION="TOTO"
ENV LDAP_DOMAIN="toto.com"
ENV LDAP_READONLY_USER="true"

# Transport Layer Security
ENV LDAP_TLS_CA_CRT_FILENAME="toto.com.crt"
ENV LDAP_TLS_CRT_FILENAME="openldap.toto.com.crt"
ENV LDAP_TLS_KEY_FILENAME="openldap.toto.com.pem"
```

**Comment by obourdon** [comment]
@mbasri as stated in my previous post of issues which could be related to this one, commenting out your line
`ENV HOSTNAME="openldap.toto.com"` makes everything worked (after verifying that it did not if the line is kept)
I am however not sure about further impacts of removing the HOSTNAME variable but seems that other people did investigate a lot on this in the same issues comments
HTH

**Comment by docfactory37** [comment]
thank you for the quick respons, i have remove all treaces of the docker container and set it up again it is all working now.

**Comment by obourdon** [comment]
@docfactory37 could you please then close the issue. Thanks
