### ISSUE TITLE
How to allow users in an OU bind access?

### ISSUE THREAD

**Issue by tlchan** [osixia/docker-openldap#45]
If readonly user is enabled, readonly has bind access with the following ACL applied during bootstrap: 

```
dn: olcDatabase={1}hdb,cn=config
changetype: modify
delete: olcAccess
-
add: olcAccess
olcAccess: to attrs=userPassword,shadowLastChange by self write by dn="cn=admin,{{ LDAP_BASE_DN }}" write by anonymous auth by * none
olcAccess: to * by self write by dn="cn=admin,{{ LDAP_BASE_DN }}" write by dn="cn={{ LDAP_READONLY_USER_USERNAME }},{{ LDAP_BASE_DN }}" read by * none
```

But how do I allow users within an OU bind access also?  Right now when binding with a user inside an OU it returns error 32 and cannot find any objects. 

```
 ldapsearch -H ldap://ldapserver -D "uid=testuser,ou=myou,dc=mydom,dc=tld" -W -b "dc=mydom,dc=tld"

# search result
search: 2
result: 32 No such object
```

Will something like this work?

```
dn: olcDatabase={1}hdb,cn=config
changetype: modify
delete: olcAccess
-
add: olcAccess
olcAccess: to attrs=userPassword,shadowLastChange by self write by dn="cn=admin,{{ LDAP_BASE_DN }}" write by anonymous auth by * none
olcAccess: to * by self write by dn="cn=admin,{{ LDAP_BASE_DN }}" write by dn="cn={{ LDAP_READONLY_USER_USERNAME }},{{ LDAP_BASE_DN }}" read by dn=“ou=myou,{{ LDAP_BASE_DN }}” read by * none
```

**Comment by tlchan** [comment]
To answer my own question, I added ```by users read``` to grant all authenticated users bind access and this works.

**Comment by osixia** [comment]
thanks for your contribution :)

**Comment by isuftin** [comment]
@tlchan Could you provide an example of this? I'm having similar issues

**Comment by lemarquois** [comment]
I'm having the same issue here as well. A bit more details would help. I tried this so far (without success): https://github.com/osixia/docker-openldap/issues/82

**Comment by tlchan** [comment]
Hi guys, sorry I have not checked github lately. It's been a while since I've work on this project...however, during docker build, I've included the following ldif to adjust the permissions to include "by users read":

```
dn: olcDatabase={1}hdb,cn=config
changetype: modify
delete: olcAccess
-
add: olcAccess
olcAccess: to attrs=userPassword,shadowLastChange by self write by dn="cn=admin,dc=mydomain,dc=io" write by anonymous auth by * none
olcAccess: to * by self write by dn="cn=admin,dc=mydomain,dc=io" write by dn="cn=readonly,dc=cncf,dc=io" read by users read by * none

```

You can also run apply it after you've spun up the container with ldapmodify command
