### ISSUE TITLE
Use explicit version of OpenLDAP in the image

### ISSUE THREAD

**Issue by nesc58** [osixia/docker-openldap#461]
Hi,
I want to contribute a version update to OpenLDAP version `2.4.51`.
I am unable to find the correct place where i can update/set the OpenLDAP version.

For me it looks like the following:
There is no explicit version used in the `Dockerfile`. Rebuilding the current image will result automatically in an update to `2.4.51`. 

So the issue is:
The rebuild of the image of version 1.4.0 (OpenLdap 2.4.50) will no longer contain the specified version but will instead contain a newer

I would suggest:
Install openldap with an explicit version
```
ENV OPENLDAP_INSTALL_VERSION=2.4.50
....
LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get -t buster-backports install -y --no-install-recommends \
    ca-certificates \
    curl \
    ldap-utils=${OPENLDAP_INSTALL_VERSION}\* \
    libsasl2-modules \
    libsasl2-modules-db \
    libsasl2-modules-gssapi-mit \
    libsasl2-modules-ldap \
    libsasl2-modules-otp \
    libsasl2-modules-sql \
    openssl \
    slapd=${OPENLDAP_INSTALL_VERSION}\* \
    slapd-contrib=${OPENLDAP_INSTALL_VERSION}\* \
    krb5-kdc-ldap \
    ....
```

The package version is e.g. `2.4.50+dfsg-1~bpo10+1` so the `\*` will be a kind of wildcard for the distribution dependant version number which contains the correct build e.g. for backports and so on (`+dfsg-1~bpo10+1`)

What do you think about this improvment?

**Comment by nesc58** [comment]
I have noticed the commit: https://github.com/osixia/docker-openldap/commit/5253671c1621b5ddcb9763cde85494a464e99a52

Should we consider using the example above to install specific version of ldap-utils and slapd-contrib as well?

**Comment by BertrandGouny** [comment]
@nesc58 sure open for a PR :)

**Comment by nesc58** [comment]
Closed by: https://github.com/osixia/docker-openldap/pull/537
