### ISSUE TITLE
How to configure a master multi-slave?

### ISSUE THREAD

**Issue by xiaoqge** [osixia/docker-openldap#47]
Here is my script:

`#!/bin/bash
LDAP_CID=$(docker run --hostname ldap.example.org --env LDAP_REPLICATION=true --env LDAP_REPLICATION_HOSTS="['ldap://ldap.example.com','ldap://ldap1.example.com
', 'ldap://ldap2.example.com']" --detach osixia/openldap:1.1.2)
LDAP_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP_CID)

LDAP1_CID=$(docker run --hostname ldap1.example.org  --detach osixia/openldap:1.1.2)
LDAP1_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP1_CID)

LDAP2_CID=$(docker run --hostname ldap2.example.org  --detach osixia/openldap:1.1.2)
LDAP2_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP2_CID)

#LDAP_CID MASTER
docker exec $LDAP_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"
docker exec $LDAP_CID bash -c "echo $LDAP1_IP ldap1.example.org >> /etc/hosts"
docker exec $LDAP_CID bash -c "echo $LDAP2_IP ldap2.example.org >> /etc/hosts"

#LDAP1_CID SLAVE
docker exec $LDAP1_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"

#LDAP2_CID SLAVE
docker exec $LDAP2_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"`

When I execute the following command such a mistake, I ask where the configuration is not correct?

`docker exec $LDAP_CID  ldapsearch -x -h ldap.example.org -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin -ZZ ldap_start_tls: Can't contact LDAP server (-1)`

@ofreax  @osixia  
Please help me to write, thank you very much

**Comment by osixia** [comment]
Hi xiaoqge,

the image provide multi-master replication configuration if you need master slave you will have to do it yourself, sorry (feel free to make a pull request). 

Take care of domain names in the example **ldap.example.org**  and **ldap.example.com** are  messed up.

To set complex bash env var at command line use `#PYTHON2BASH:`

here a working example :

```
#!/bin/bash
LDAP_CID=$(docker run --hostname ldap.example.com --env LDAP_REPLICATION="true" --env LDAP_REPLICATION_HOSTS="#PYTHON2BASH:['ldap://ldap.example.com','ldap://ldap1.example.com', 'ldap://ldap2.example.com']" --detach osixia/openldap:1.1.2)
LDAP_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP_CID)

LDAP1_CID=$(docker run --hostname ldap1.example.com --env LDAP_REPLICATION="true" --env LDAP_REPLICATION_HOSTS="#PYTHON2BASH:['ldap://ldap.example.com','ldap://ldap1.example.com', 'ldap://ldap2.example.com']" --detach osixia/openldap:1.1.2)
LDAP1_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP1_CID)

LDAP2_CID=$(docker run --hostname ldap2.example.com --env LDAP_REPLICATION="true" --env LDAP_REPLICATION_HOSTS="#PYTHON2BASH:['ldap://ldap.example.com','ldap://ldap1.example.com', 'ldap://ldap2.example.com']" --detach osixia/openldap:1.1.2)
LDAP2_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP2_CID)

#LDAP_CID MASTER
docker exec $LDAP_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"
docker exec $LDAP_CID bash -c "echo $LDAP1_IP ldap1.example.org >> /etc/hosts"
docker exec $LDAP_CID bash -c "echo $LDAP2_IP ldap2.example.org >> /etc/hosts"

#LDAP1_CID SLAVE
docker exec $LDAP1_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"
docker exec $LDAP1_CID bash -c "echo $LDAP1_IP ldap1.example.org >> /etc/hosts"
docker exec $LDAP1_CID bash -c "echo $LDAP2_IP ldap2.example.org >> /etc/hosts"


#LDAP2_CID SLAVE
docker exec $LDAP2_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"
docker exec $LDAP2_CID bash -c "echo $LDAP1_IP ldap1.example.org >> /etc/hosts"
docker exec $LDAP2_CID bash -c "echo $LDAP2_IP ldap2.example.org >> /etc/hosts"
```

**Comment by xiaoqge** [comment]
@osixia Thank you very much, multi-master can only have a maximum of two containers do? Not more? I try to configure multiple master host, but does not work? Is there more than two configuration examples of MASTER. Thank you very much

**Comment by osixia** [comment]
the 3 containers are master and it should works, what king of error do you have ?

**Comment by xiaoqge** [comment]
@osixia I modified the script:
`#!/bin/bash
LDAP_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP_CID)

LDAP1_CID=$(docker run --hostname ldap1.example.org --env LDAP_REPLICATION="true" --env LDAP_REPLICATION_HOSTS="#PYTHON2BASH:['ldap://ldap.example.org','ld
ap://ldap1.example.org', 'ldap://ldap2.example.org']" --detach osixia/openldap:1.1.2)
LDAP1_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP1_CID)

LDAP2_CID=$(docker run --hostname ldap2.example.org --env LDAP_REPLICATION="true" --env LDAP_REPLICATION_HOSTS="#PYTHON2BASH:['ldap://ldap.example.org','ld
ap://ldap1.example.org', 'ldap://ldap2.example.org']" --detach osixia/openldap:1.1.2)
LDAP2_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP2_CID)

#LDAP_CID MASTER
docker exec $LDAP_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"
docker exec $LDAP_CID bash -c "echo $LDAP1_IP ldap1.example.org >> /etc/hosts"
docker exec $LDAP_CID bash -c "echo $LDAP2_IP ldap2.example.org >> /etc/hosts"

#LDAP1_CID SLAVE
docker exec $LDAP1_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"
docker exec $LDAP1_CID bash -c "echo $LDAP1_IP ldap1.example.org >> /etc/hosts"
docker exec $LDAP1_CID bash -c "echo $LDAP2_IP ldap2.example.org >> /etc/hosts"


#LDAP2_CID SLAVE
docker exec $LDAP2_CID bash -c "echo $LDAP_IP ldap.example.org >> /etc/hosts"
docker exec $LDAP2_CID bash -c "echo $LDAP1_IP ldap1.example.org >> /etc/hosts"
docker exec $LDAP2_CID bash -c "echo $LDAP2_IP ldap2.example.org >> /etc/hosts"
~                                                                             `

Try and start three master, but the first three Master appears unexpectedly quit, here is the log:

`*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:cfssl/startup.sh to /container/run/startup/:cfssl
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
  ution: previously defined variables will not be overriden.
[6nntainer/environment/99-default/default.yaml.startup
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:cfssl...
*** Running /container/run/startup/slapd...
Database and config directory are empty...
Init new ldap server...
invoke-rc.d: policy-rc.d denied execution of stop.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.19-18+deb8u3) ...
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add bootstrap schemas...
*** /container/run/startup/slapd failed with status 255

*** Killing all processes...`




Another problem is the possibility of support from the main one? This image only supports multi-master it? If the master-slave mode is the need to expand their IMAGE it?

**Comment by osixia** [comment]
I see only 2 container started in your script and you try to get the ip from an non existing container 
LDAP_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $LDAP_CID)

i don't understand what you are trying to do...

**Comment by xiaoqge** [comment]
@osixia  I'm sorry, but when I copied line is missing, please help me have a look, thank you

**Comment by xiaoqge** [comment]
Thank you, I re-configured the script, you can now master-slave mode
https://github.com/xiaoqge/docker-openldap/blob/stable/README.md#master-slave-replication
@osixia
