### ISSUE TITLE
chown: cannot access '/container/service/slapd/assets/certs/ca.crt': No such file or directory

### ISSUE THREAD

**Issue by electricduck** [osixia/docker-openldap#488]
Built my container this morning and had to quickly restart it, and it no longer wants to start up, throwing the above error.

```*** CONTAINER_LOG_LEVEL = 3 (info),
*** Search service in CONTAINER_SERVICE_DIR = /container/service :,
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools,
*** failed to link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools: [Errno 17] File exists: '/container/service/:ssl-tools/startup.sh' -> '/container/run/startup/:ssl-tools',
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd,
*** failed to link /container/service/slapd/startup.sh to /container/run/startup/slapd: [Errno 17] File exists: '/container/service/slapd/startup.sh' -> '/container/run/startup/slapd',
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run,
*** directory /container/run/process/slapd already exists,
*** failed to link /container/service/slapd/process.sh to /container/run/process/slapd/run : [Errno 17] File exists: '/container/service/slapd/process.sh' -> '/container/run/process/slapd/run',
*** Set environment for startup files,
*** Environment files will be proccessed in this order : ,
Caution: previously defined variables will not be overriden.,
/container/environment/99-default/default.yaml,
/container/environment/99-default/default.startup.yaml,
,
To see how this files are processed and environment variables values,,
run this container with '--loglevel debug',
*** Running /container/run/startup/:ssl-tools...,
*** Running /container/run/startup/slapd...,
openldap user and group adjustments,
get current openldap uid/gid info inside container,
-------------------------------------,
openldap GID/UID,
-------------------------------------,
User uid: 1002,
User gid: 1002,
uid/gid changed: false,
-------------------------------------,
updating file uid/gid ownership,
chown: cannot access '/container/service/slapd/assets/certs/ca.crt': No such file or directory,
*** /container/run/startup/slapd failed with status 1,
,
*** Killing all processes...,```

**Comment by CodingJaw** [comment]
chown: cannot access '/container/service/slapd/assets/certs/ca.crt': No such file or directory,

im new to openldap so take this as a grain of salt.... but seems like you have told openldap to use tls without generating the certs its trying to 
`chown openldap /container/service/slapd/assets/certs/ca.crt`
which failed because its not there try using
      - LDAP_TLS=false
      - LDAP_TLS_VERIFY_CLIENT=false

or change the locations to match your certs

      - LDAP_TLS_CRT_FILENAME=certificate.crt
      - LDAP_TLS_KEY_FILENAME=privatekey.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.pem

or use the autogen certs
see https://github.com/osixia/docker-openLDAP#tls
> TLS
> Use auto-generated certificate
> 
> By default, TLS is already configured and enabled, certificate is created using container hostname (it can be set by docker run --hostname option eg: ldap.example.org).
> 
> docker run --hostname ldap.my-company.com --detach osixia/openldap:1.4.0

but im sure if you want more help your going to need to post your compose file so we can see what is setup.
