### ISSUE TITLE
mail.schema: line 21 attributetype: Inconsistent duplicate attributeType: "mailalias"

### ISSUE THREAD

**Issue by williamdes** [osixia/docker-openldap#502]
```
 5fe895b4 /container/service/slapd/assets/config/bootstrap/schema/mmc/mail.schema: line 21 attributetype: Inconsistent duplicate attributeType: "mailalias"
```

**Comment by williamdes** [comment]
I am quite sure this is why https://github.com/tomav/docker-mailserver/blob/59ba34cb4bdd90455aede772d330701710691ee2/test/docker-openldap/Dockerfile#L5 exists

**Comment by stettberger** [comment]
This is fixed in v1.50 as mmc/mail.schema was removed, or?

**Comment by williamdes** [comment]
Probably not, see my fix
https://github.com/desportes/infrastructure/blob/main/dockers/docker-openldap/Dockerfile

Not sure about my comment but maybe it will help

**Comment by williamdes** [comment]
Closing, nobody cares about this repository. Me too, I re-built the project: https://github.com/sudo-bot/docker-openldap#readme
