### ISSUE TITLE
Mounting volumes via docker-compose

### ISSUE THREAD

**Issue by phlegx** [osixia/docker-openldap#51]
Dear all,

I'm currently on version 1.1.2 of this awesome docker image. 

Here is my problem: With ```docker``` (tested versions ```1.10.0``` and ```1.11.0```)  and ```docker-compose``` (tested versions ```0.6.2``` and ```0.7.0```) I try to mount the volumes like this:

```    
volumes:
    - /root/docker_data/openldap/ldap /var/lib/ldap
    - /root/docker_data/openldap/slapd.d /etc/ldap/slapd.d
```

However the directories are not created when I bring up your openldap image via ```docker-compose```. 

When I start the image via docker run like i.e.

```
docker run --volume /root/docker_data/openldap/ldap:/var/lib/ldap \
--volume /root/docker_data/openldap/slapd.d:/etc/ldap/slapd.d
--detach osixia/openldap:1.1.2
```
The volumes are created just fine in  ```/root/docker_data/openldap/```.
Any ideas what might be wrong? I did several mountings now already via ```docker-compose``` with other images, however it always worked just as expected. Not sure why with this image it would not work.

thanks!

**Comment by EugenMayer** [comment]
you syntax is simply wrong

```
- /root/docker_data/openldap/ldap:/var/lib/ldap
```

**Comment by phlegx** [comment]
Thank you @EugenMayer at some point I discovered that I made that syntax error and fixed it. Forgot that I wrote the comment here! I'll close it.
