### ISSUE TITLE
Multi replication failed, TLS negotiation failuer 

### ISSUE THREAD

**Issue by wayilau** [osixia/docker-openldap#517]
Hi,
I met a problem when i use multi replication feature.  is there someone help me ?
![image](https://user-images.githubusercontent.com/3197838/105133499-dcba9680-5b27-11eb-921b-dd8b4a8746b4.png)

**Comment by calen3** [comment]
root CA certs expired. I got information as:
`TLSMC: MozNSS compatibility interception ends.
TLS trace: SSL_connect:before/connect initialization
TLS trace: SSL_connect:SSLv2/v3 write client hello A
TLS trace: SSL_connect:SSLv3 read server hello A
TLS certificate verification: depth: 1, err: 10, subject: /C=US/O=A1A Car Wash/OU=Information Technology Dep./L=Albuquerque/ST=New Mexico/CN=docker-light-baseimage, issuer: /C=US/O=A1A Car Wash/OU=Information Technology Dep./L=Albuquerque/ST=New Mexico/CN=docker-light-baseimage
TLS certificate verification: Error, certificate has expired
TLS trace: SSL3 alert write:fatal:certificate expired`
In my case , - LDAP_TLS=fasle

**Comment by wayilau** [comment]
expired ? did not it renew in every create ? i have seen date in the certs files, it is not expired, what's the meaning?

**Comment by calen3** [comment]
> expired ? did not it renew in every create ? i have seen date in the certs files, it is not expired, what's the meaning?

CA cert， not host‘s cert.  I tryed "- LDAP_TLS=fasle" but error still yet.....

**Comment by wayilau** [comment]
use master slave instead.

**Comment by invent-lwj** [comment]
> use master slave instead.

How to config master slave?
Thanks!
