### ISSUE TITLE
Docker Compose compilation of options

### ISSUE THREAD

**Issue by cfairweather** [osixia/docker-openldap#52]
This project looks promising! I'm thinking it will work as part of another project I'm working on.

I'm suggesting the project create and commit a `docker-compose.yml` with `image` references to automated Docker Hub builds providing examples of environment variables and container name for users wishing to both deploy the pre-built images or build them locally. 

Instead of providing one-off examples of `docker run` commands, provide your suggested "defined infrastructure" setup by way of a `docker-compose.yml` file.

I'm thinking something link [this](https://github.com/Annixa/docker-nginx-letsencrypt-proxy/blob/master/docker-compose-production.yml) might be an example?

**Comment by osixia** [comment]
Great idea,
but i don't have the time for now to do that, if you have a working example i can add it :)

Thanks

**Comment by EugenMayer** [comment]
Well, here is one :) https://github.com/EugenMayer/kontextwork-catalog/blob/master/tests/openldap/docker-compose.yml
