### ISSUE TITLE
Cannot persistently set the admin password

### ISSUE THREAD

**Issue by basschaser** [osixia/docker-openldap#559]
Hi, I am unable to set the admin password persistently and in a secure manner.

I am trying to do so through the use of custom ldif on first boot, simply to replace the weak default encryption. The password change works initially, but on container reboot it is reset to the default password 'admin'.
This appears to be the same issue as #522 

Using the ldif below, I am able to set the password successfully:
```
# Change admin/schema password
dn: olcDatabase={1}{{ LDAP_BACKEND }},cn=config
changetype: modify
replace: olcRootPW
olcRootPW: {CRYPT}[ REDACTED ]
```

However the change always reverts to the default password on container reboot.

Futhermore I am trying to change the password of the 'extra' admin account, per #161, using this ldif:
```
# Admin password
dn: cn=admin,{{ LDAP_BASE_DN }}
changetype: modify
replace: userPassword
userPassword: {CRYPT}[ REDACTED ]
```

But get this error message during bootstrap: `ldap_modify: No such object (32)`

Has the 'extra' account been fixed in recent images, and this is no longer necessary?

**Comment by M4n1us** [comment]
I am also running into this problem, have you found a fix?

**Comment by basschaser** [comment]
@M4n1us 

I ended up fixing it by using the YAML to set the passwords instead. Somehow I must have glanced over the `KEEP_EXISTING_CONFIG` variable.

Thanks for the heads up, closing this issue.
