### ISSUE TITLE
ldap + kerberos integration

### ISSUE THREAD

**Issue by typekpb** [osixia/docker-openldap#57]
I need to achieve ldap + kerberos integration. 
Currently I'm following: https://help.ubuntu.com/lts/serverguide/kerberos-ldap.html
however I'm stuck, there seems to be missing file: `/usr/share/doc/krb5-kdc-ldap/kerberos.schema.gz`.

Running:

    apt-get update && apt-get upgrade -yy && apt-get install -yy  krb5-kdc-ldap && ls -l /usr/share/doc/krb5-kdc-ldap/kerberos.schema.gz

Inside the container: `osixia/openldap:1.1.2` there is no such file. Any idea why it is so? 

however if I ran:

    apt-get update && apt-get install -yy apt-file && apt-file update && apt-file list krb5-kdc-ldap

I see:

	krb5-kdc-ldap: /etc/insserv/overrides/krb5-kdc
	krb5-kdc-ldap: /lib/systemd/system/krb5-admin-server.service.d/slapd-before-kdc.conf
	krb5-kdc-ldap: /lib/systemd/system/krb5-kdc.service.d/slapd-before-kdc.conf
	krb5-kdc-ldap: /usr/lib/x86_64-linux-gnu/krb5/libkdb_ldap.so.1
	krb5-kdc-ldap: /usr/lib/x86_64-linux-gnu/krb5/libkdb_ldap.so.1.0
	krb5-kdc-ldap: /usr/lib/x86_64-linux-gnu/krb5/plugins/kdb/kldap.so
	krb5-kdc-ldap: /usr/sbin/kdb5_ldap_util
	krb5-kdc-ldap: /usr/share/doc/krb5-kdc-ldap/NEWS.Debian.gz
	krb5-kdc-ldap: /usr/share/doc/krb5-kdc-ldap/changelog.Debian.gz
	krb5-kdc-ldap: /usr/share/doc/krb5-kdc-ldap/copyright
	krb5-kdc-ldap: /usr/share/doc/krb5-kdc-ldap/kerberos.ldif.gz
	krb5-kdc-ldap: /usr/share/doc/krb5-kdc-ldap/kerberos.schema.gz
	krb5-kdc-ldap: /usr/share/man/man8/kdb5_ldap_util.8.gz

moreover, if I ran the command inside the `debian:jessie` docker container: 

       apt-get update && apt-get upgrade -yy && apt-get install -yy  krb5-kdc-ldap && ls -l /usr/share/doc/krb5-kdc-ldap/kerberos.schema.gz

I can see the file present.

Why is it so?

**Comment by osixia** [comment]
Hi,
this image had a configuration to prevent documentation and locales to be installed to make it more lightweight as possible.

to install doc remove the file **/etc/dpkg/dpkg.cfg.d/01_nodoc**
```
rm -f /etc/dpkg/dpkg.cfg.d/01_nodoc
```
and for locales **/etc/dpkg/dpkg.cfg.d/01_nolocales**
```
rm -f /etc/dpkg/dpkg.cfg.d/01_nolocales
```

After that install  **krb5-kdc-ldap** and **/usr/share/doc/krb5-kdc-ldap/kerberos.schema.gz** file should be there :)

I will add a note in the documentation sorry about that.

**Comment by typekpb** [comment]
@osixia thanks! Feel free to close this issue.

**Comment by svdba** [comment]
It doesn't help. There is extra file /etc/dpkg/dpkg.cfg.d/docker with similar content. You better add include section to the file. For example `echo "path-include /usr/share/doc/krb5*" >> /etc/dpkg/dpkg.cfg.d/docker`

**Comment by leolorenzoluis** [comment]
@svdba New to this. What do you mean include section to the file? Do I need to delete those extra files under /dpkg?

**Comment by osixia** [comment]
@svdba thanks for the info, can you make a pull request for that ?

**Comment by osixia** [comment]
@leolorenzoluis it seems that now debian baseimage also add on configuration file to not install docs. remove also file `/etc/dpkg/dpkg.cfg.d/docker`

**Comment by leolorenzoluis** [comment]
@osixia Thanks for the reply. I have removed the file, but I still get the same situation. No files downloaded.

**Comment by svdba** [comment]
@osixia @leolorenzoluis I've added PR #171

**Comment by KanoWill** [comment]
I met this issue today, but the solutions above didn't work, I think it is caused by the new version of the ubuntu image.
I solved this problem with the below command
```bash
sed -i 's/path-exclude=\/usr\/share\/doc\/\*/#path-exclude=\/usr\/share\/doc\/*/' 
apt reinstall krb5-kdc-ldap
```
