### ISSUE TITLE
Startup stucks at "slapd starting"

### ISSUE THREAD

**Issue by psychofaktory** [osixia/docker-openldap#598]
The docker won't start up.
Everytime it stucks at "slapd starting"

I had to remove the "hostname" variable before becaus of the "failed errno=98 (Address already in use)" like mentioned  #530

Here is the log
[log.txt](https://github.com/osixia/docker-openldap/files/7566015/log.txt)

**Comment by psychofaktory** [comment]
The issue can be deleded.

**Comment by MichalNemec** [comment]
how did you solve this?
