### ISSUE TITLE
docker-compose example ?

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#60]
I am trying to run this server with docker-compose : 

  ldap:
    build: image
    hostname: ldap.kopaxgroup.com
    environment: 
      - LDAP_ORGANISATION=kopaxgroup
      - LDAP_DOMAIN=kopaxgroup.com
      - LDAP_ADMIN_PASSWORD=pw
      - LDAP_TLS_CIPHER_SUITE=NORMAL
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_TLS_CRT_FILENAME=wildcard.domain.crt
      - LDAP_TLS_KEY_FILENAME=wildcard.domain.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_READONLY_USER=false
      - LDAP_READONLY_USER_USERNAME=client
      - LDAP_READONLY_USER_PASSWORD=pw
      - LDAP_LOG_LEVEL=256
    volumes:
      - /tmp/ldap/var/lib/ldap:/var/lib/ldap
      - /tmp/ldap/etc/slapd.d:/etc/ldap/slapd.d
      - ./certs:/container/service/slapd/assets/certs
    ports:
      - "389:389"
      - "636:636"

Sometimes the server crash, somestimes it start.
I feel like my certs aren't working well.
I am using the one from my postfix server, is it correct or should I compile file differently ?

I have also tried to start it with the ldapphpadmin.

    ldap:
      build: image
      hostname: ldap.domaine.com
      environment: 
        - LDAP_ORGANISATION=domaine
        - LDAP_DOMAIN=domaine.com
        - LDAP_ADMIN_PASSWORD=pw
        - LDAP_TLS_CIPHER_SUITE=NORMAL
        - LDAP_TLS_VERIFY_CLIENT=never
        - LDAP_TLS_CRT_FILENAME=wildcard.domaine.crt
        - LDAP_TLS_KEY_FILENAME=wildcard.domaine.key
        - LDAP_TLS_CA_CRT_FILENAME=ca.crt
        - LDAP_READONLY_USER=false
        - LDAP_READONLY_USER_USERNAME=client
        - LDAP_READONLY_USER_PASSWORD=pw
        - LDAP_LOG_LEVEL=256
      volumes:
        - /tmp/ldap/var/lib/ldap:/var/lib/ldap
        - /tmp/ldap/etc/slapd.d:/etc/ldap/slapd.d
        - ./certs:/container/service/slapd/assets/certs
      ports:
        - "389:389"
        - "636:636"
    ldapadmin:
      image: osixia/phpldapadmin:0.6.9
      hostname: ldapadmin.domaine.com
      environment: 
        - PHPLDAPADMIN_HTTPS=true
        - PHPLDAPADMIN_HTTPS_CRT_FILENAME=wildcard.domaine.com.crt
        - PHPLDAPADMIN_HTTPS_KEY_FILENAME=wildcard.domaine.com.key
        - PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME=ca.crt
        - PHPLDAPADMIN_LDAP_HOSTS=ldap1
      volumes:
        - /ldapadmin/my-config.php:/container/service/phpldapadmin/assets/config.php
        - ./certs:/container/service/phpldapadmin/assets/apache2/certs
      ports:
        - "6443:443"
      links:
        - "ldap:ldap1"

Could you show us an example of a working docker-compose file, that would help :)

**Comment by osixia** [comment]
Hi,
please see #52
