### ISSUE TITLE
Auto generated file, why can't we edit ?

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#61]
Inside configurations files from the `slapd.d` directory, there is a comment in every files:

	# AUTO-GENERATED FILE - DO NOT EDIT!! Use ldapmodify.

I need to add the following features :

1. access control read and read/write.
1. required and protected email field in my user schema

I have tried to mount a volume in `./scripts:/scripts` and execute this command : 

    docker exec -ti openldap ldapadd -x -D "cn=admin,dc=mydomain,dc=com" -W -f /scripts/exampleConfiguration.ldif

With __exampleConfiguration.ldif__ : sample configuration file from the [OpenLDAP Admin User Guide 2.4](http://www.openldap.org/doc/admin24/slapdconf2.html#Configuration Example)

	# example config file - global configuration entry
	dn: cn=config
	objectClass: olcGlobal
	cn: config
	olcIdleTimeout: 30
	olcLogLevel: Stats
	olcReferral: ldap://root.openldap.org

	# internal schema
	dn: schema, cn=config
	objectClass: olcSchemaConfig
	cn: schema

	# include the core schema
	include: /scripts/core.ldif

	# global database parameters
	dn: olcDatabase=frontend,cn=config
	objectClass: olcDatabaseConfig
	olcDatabase: frontend
	olcAccess: to * by * read

	# set a rootpw for the config database so we can bind.
	# deny access to everyone else
	dn: olcDatabase=config,cn=config
	objectClass: olcDatabaseConfig
	olcDatabase: config
	olcRootPW: {MD5}b295ab91a73ae7049c0ba523c03511e3
	oldAccess: to * by * none

	# BDB definition for mydomain.com
	dn: olcDatabase=bdb,cn=config
	objectClass: olcDatabaseConfig
	objectClass: olcBdbConfig
	olcDatabase: bdb
	olcSuffix: dc=mydomain,dc=com
	olcDbDirectory: /var/lib/ldap
	olcRootDN: cn=Manager,dc=mydomain,dc=com
	olcRootpw: secret
	olcDbIndex: uid pres,eq
	olcDbIndex: cn,sn pres,eq,approx,sub
	olcDbIndex: objectClass eq
	olcAccess: to attrs=userPassword
	 by self write
	 by anonymous auth
	 by dn.base="cn=admin,dc=mydomain,dc=com" write
	 by * none
	olcAccess: to *
	 by self write
	 by dn.base="cn=admin,dc=example,dc=com" write
	 by * read

	# BDB definition for mydomain.com
	dn: olcDatabase=bdb,cn=config
	objectClass: olcDatabaseConfig
	objectClass: olcBdbConfig
	olcDatabase: bdb
	olcSuffix: "dc=mydomain,dc=net"
	olcDbDirectory: /var/lib/ldap
	olcRootDN: "cn=Manager,dc=mydomain,dc=com"
	olcDbIndex: objectClass eq
	olcAccess: to * by users read

But I have the following error : 

    Enter LDAP Password: 
    adding new entry "cn=config"
    ldap_add: Insufficient access (50)

1. Is it safe to edit these files?
1. If I edit the files, will it be re-generated at next container start? 
1. what is the appropriate way to make permanent modification?
1. Is `cn=admin` the _super-user_?

**Comment by kopax** [comment]
partially solved.

There is an example on how to extend in example/extend-osixia-openldap.

I managed to create users, groups, organizationalUnit, countries.

But I wasn't able to load any configuration file like: 

    dn: cn=module,cn=config
    changetype: add
    cn: module
    objectClass: olcModuleList
    olcModuleLoad: memberof
    olcModulePath: /var/lib/ldap

Everytime I end up with error:

     ldap_add: Insufficient access (50)

Regarding theses links: http://idmoim.blogspot.com/2014/05/ldapadd-insufficient-access-50-openldap.html , there might have an error with the admin that should be named manager. It is not very clear. Does anyone has ever noticed this ?

**Comment by osixia** [comment]
please refer to the openldap documentation

**Comment by benlangfeld** [comment]
@osixia By any chance could you be more specific about why this was closed? I am unsure how to move forward, despite copying precisely the examples per https://github.com/osixia/docker-openldap/issues/48#issuecomment-290112983
