### ISSUE TITLE
Can't use memberOf, is there an alternative way to check user by groups?

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#63]
I have created a group by adding a file in `bootstrap/ldif/group.ldif` using 

    dn: cn=jenkins_admins,ou=groups,ou=developers,dc=domain,dc=com
    changetype: add
    cn: Jenkins Administrators
    description: Staff members allowed to login to jenkins build system
    member: uid=me,ou=users,ou=developers,dc=,dc=com
    objectclass: groupOfNames
    objectclass: top

I then run a query in __phpLDAPadmin__ with this filter  

    (&(objectClass=posixAccount)(memberOf=cn=jenkins_admins,ou=groups,ou=developers,dc=domain,dc=com))

Showing no results.

I struggle getting the memberOf filter working, does anyone has some explanation to share?
Is there an alternative way to check user by groups?

**Comment by davidsan** [comment]
You might need to change `groupOfNames `to `groupOfUniqueNames`.

**Comment by kopax** [comment]
I might add some more users in the futur in this group.
And that doesn't explain why the filter isn't working.

**Comment by kopax** [comment]
Solved, problem was that user has to be created before the group, otherwise user doesn't have the memberOf attribute
