### ISSUE TITLE
Readonly account doesn't work

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#64]
With a fresh db install, I have the following : 

    openldap        | Add read only user...
    openldap        | Processing file /container/service/slapd/assets/config/bootstrap/ldif/readonly-user/readonly-user.ldif
    openldap        | adding new entry "cn=readonly,dc=domain,dc=com"
    openldap        | Processing file /container/service/slapd/assets/config/bootstrap/ldif/readonly-user/readonly-user-acl.ldif
    openldap        | ldap_modify: No such object (32)
    openldap        | *** /container/run/startup/slapd failed with status 32
    openldap        | 
    openldap        | *** Killing all processes...

The creation fails with the files `bootstrap/ldif/readonly-user/readonly-user-acl.ldif`,

     dn: olcDatabase={1}{{ LDAP_BACKEND }},cn=config

With `LDAP_BACKEND=hdb`

But, the file `02-security.ldif` which also has the same syntax work well.

I have tried to swap the content of files in every order, I wasn't able to make it work.

**Comment by kopax** [comment]
It appear that the problem comes from the fact that `{{ LDAP_BASE_DN }` is not available for create when the scripts try to execute it.

By moving it's content in a file `bootstrap/ldif/99-perms.ldif`, the user successfully create.
_be careful to change the interpolated string as the startup script does target not interpolate strings in your file_

This could be fixed by being able to delay it's importation.

**Comment by osixia** [comment]
Hello,
this will be fixed in the next release thanks to @danielpanteleit 

see pull request #62

Thanks :)
