### ISSUE TITLE
Why is my docker run creating my domain as an organization not a domain

### ISSUE THREAD

**Issue by migace001** [osixia/docker-openldap#641]
Trying to figure out why my dc=test,dc=test1 when i click on it says its a organization not a domain. Driving me nuts the openldap docker seems easy but it  seem to get around it.

**Comment by migace001** [comment]
I sure can, I have an existing openldap server, i have gotten my ldifs that i need to import. When i use the osixia openldap it creates an organizational unit rather than a domain. I have attached a sreenshot of my original domain definition and the definition that gets created with the osixia, I need it to be defined as top domain so that my backup ldif can import definitions into it. Capture 1 is what i get with osixia openldap, Capture 2 was a manual build. What do i have to do to get it defined as like Capture 2.     On Monday, October 24, 2022, 12:58:42 PM CDT, João E. Pereira Jr ***@***.***> wrote:  
 
 


Hello @migace001,
Could you provide more details about the issue?

**Comment by joaoepj** [comment]
@migace001,

Sorry, I could'nt find the screenshots. Check if the  LDAP_ORGANISATION and LDAP_DOMAIN enrironment variables are properly set when starting the container via docker-composer. Inspect the containers and compare the outputs.

**Comment by migace001** [comment]
![Capture1](https://user-images.githubusercontent.com/115584182/198303330-d4f68fcb-b67f-4621-a43e-1d0f62733902.PNG)
![Capture2](https://user-images.githubusercontent.com/115584182/198303368-b7fa3b5e-db12-497c-922a-9282f7eca2d2.PNG)
Here is what i a reffering to

**Comment by joaoepj** [comment]
@migace001,

I see. As far as I know using organization as the sctructural attribute in this scenario is the right behaviour. openldap also defines domain objectClasses to be used in other scenarios like DNS or email. In your case the domain is test.test1, but presented in 2 domain components dc=test,dc=test1. I think you shold proceed this way and things will work as expected.
