### ISSUE TITLE
LDAP_TLS_ENFORCE=true is it correct ?

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#65]
The env var `LDAP_TLS_ENFORCE=true` will require secure connection over TLS regarding the env var name.

I have set this to true, and I can connect using SSL with jenkins and gitlab "ldaps://"

According to my understand : 

- LDAPS is SSL, direct encryption handshake at connection on port 636
- LDAP with TLS is encryption handshaking after STARTTLS on port 389

Does it mean LDAP_TLS_ENFORCE accept both ?

**Comment by osixia** [comment]
hello,
please refer to #26
