### ISSUE TITLE
Way to activate --log-level for marathon

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap#66]
I want to deploy this container using marathon.
Does anyone knows how to activate the `--log-level debug` ? 
I have tried with args ["/container/service/run","--log-level", "debug"] , I see `--log-level`  but the container crash on boot without any debug informations.

**Comment by jgehrcke** [comment]
Just omit the first arg.

https://docs.docker.com/engine/reference/run/

That's the signature:

```
$ docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]
```

I did not run the container via Marathon, but using the scheme above, I have successfully spawned it this way:

```
$ docker run [OPTIONS] IMAGE[:TAG|@DIGEST] --log-level debug
```

**Comment by kopax** [comment]
I was able from the command line also. I keep this open until somebody share a way to do it with marathon.

**Comment by koboltmarky** [comment]
you can use cmd with 

"cmd": "/container/service/run --log-level debug"

**Comment by kopax** [comment]
according to https://github.com/mesosphere/marathon/issues/4066#issuecomment-231041575 , it should be appended using `container.docker.parameters`
