### ISSUE TITLE
LDAP_TLS_PROTOCOL_MIN ignored, LDAP_TLS_CIPHER_SUITE only faintly compatible

### ISSUE THREAD

**Issue by jgehrcke** [osixia/docker-openldap#69]
#### LDAP_TLS_PROTOCOL_MIN

From the readme:
```
LDAP_TLS_PROTOCOL_MIN: TLS min protocol. Defaults to 3.1
```

Note that this translates to the `olcTLSProtocolMin` setting documented here: http://man7.org/linux/man-pages/man5/slapd-config.5.html

Quote:
> This directive is ignored with GnuTLS.

The base image here uses Debian Jessie: https://github.com/osixia/docker-light-baseimage/blob/stable/image/Dockerfile

slapd in Jessie is built against GnuTLS: https://packages.debian.org/jessie/slapd
```
dep: libgnutls-deb0-28 (>= 3.3.0)
```

So, this should not have an effect. If it did, I'd argue we should set it to `3.2` to enforce TLS 1.2, but see below.

#### LDAP_TLS_CIPHER_SUITE

From the readme:
```
LDAP_TLS_CIPHER_SUITE: TLS cipher suite. Defaults to SECURE256:-VERS-SSL3.0
```

A Python 3.4.5 client built against a Fedora 23 OpenSSL cannot connect to that server, and that changes when setting `LDAP_TLS_CIPHER_SUITE` to `NORMAL`. So, let's make this more _compatible_. I suppose that `-VERS-SSL3.0` does not exclude SSL 2 (I may be wrong here), and I suggest that we use the CIPHER string to limit the protocol to TLS 1.2 to also make this more _secure_ (and in order to compensate for olcTLSProtocolMin not taking effect).

##### TLS protocol version
Why not TLS 1.0?
https://blog.varonis.com/ssl-and-tls-1-0-no-longer-acceptable-for-pci-compliance/
> The PCI Council says you must remove completely support for SSL 3.0 and TLS 1.0. In short: servers and clients should disable SSL and then preferably transition everything to TLS 1.2.

While 1.1 is still considered "secure" if properly cofigured, I'd say let's just default this to 1.2 here. Related:
https://www.wolfssl.com/wolfSSL/Blog/Entries/2010/12/14_A_Comparison_of_TLS_1.1_and_TLS_1.2.html

[Red Hat about TLS 1.1](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Hardening_TLS_Configuration.html):
> Use for interoperability purposes where needed. Has no known issues but relies on protocol fixes that are included in all the TLS implementations in Red Hat Enterprise Linux. Does not support modern cipher suites.

##### Ciphers

I suppose we _could_ simply use `NORMAL`, because the container uses a sufficiently new GnuTLS (3.3.8, according to https://packages.debian.org/jessie/libgnutls-deb0-28).

"NORMAL" should be safe according to http://www.hep.by/gnu/gnutls/Priority-Strings.html:
> NORMAL: Means all the known to be secure ciphersuites.

It's a little tedious to find really good examples of production-proven GnuTLS cipher strings on the web (there is way more material for OpenSSL).

But I suppose this is a rather good source:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Hardening_TLS_Configuration.html

That source suggests:
```
SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC
```

Note how it explicitly disables all SSL/TLS protocol versions and then selectively enables TLS protocol version 1.2. 

I have confirmed that `SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC` makes my setup (Python 3.4.5 client built against a Fedora 23 OpenSSL, see above) work against the container.

So, I suggest implementing this and following [Red Hat's cipher hardening guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Hardening_TLS_Configuration.html) over time.

**Comment by osixia** [comment]
Thanks a lot, 
i will fix that asap and add a note in the readme to keep the red hat guide cipher as reference :)

**Comment by jgehrcke** [comment]
> i will fix that asap
Oh, I have just submitted a PR. I hope we didn't overlap now. You are fast :).
