### ISSUE TITLE
Error in Adding "Billy"

### ISSUE THREAD

**Issue by butterhc** [osixia/docker-openldap#71]
docker exec $LDAP_CID ldapadd -x -D "cn=admin,dc=example,dc=org" -w admin -f /container/service/slapd/assets/test/new-user.ldif --hostname ldap.example.org -ZZ

ldapadd: invalid option -- '-'
ldapadd: unrecognized option --

I had to remove --hostname ldap.example.org in order for the command to complete.

**Comment by osixia** [comment]
Hello,
this is a typo in the readme thanks :)

use -h ldap.example.org (refer to test/test.bats part "replication with new databases and strict TLS" for a working example)
