### ISSUE TITLE
Upgrade to 1.1.5 startup issues with cfssl-helper

### ISSUE THREAD

**Issue by adamlc** [osixia/docker-openldap#73]
Whilst upgrading to 1.1.5 the container is no longer able to startup. I have the following error when the container is starting:

```shell
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:cfssl/startup.sh to /container/run/startup/:cfssl
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml
/container/environment/99-default/default.yaml.startup

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:cfssl...
*** Running /container/run/startup/slapd...
Usage: cfssl-helper prefix cert_file key_file ca_file
*** /container/run/startup/slapd failed with status 1

*** Killing all processes...
```

I'm using my own SSL certs called the default names, ldap.crt, ldap.key and ca.crt etc. Not sure what's changed but something no longer works :(

**Comment by adamlc** [comment]
Downgrading also doesn't work because of #44. So I guess the 2 are related?

**Comment by osixia** [comment]
Hi, are you mounting an existing database/config ?

**Comment by adamlc** [comment]
Yes I'm mounting the ones from the old version. This is a replicated node, not sure if that makes any difference. I'm injecting the SSL keys in the docker build process

**Comment by osixia** [comment]
can you try with osixia/openldap:1.1.6 ?
take care to use the same certificate filenames as when the config was created

**Comment by adamlc** [comment]
Just had a thought. I've changed the olcAccess on the other servers using ldapmodify (ldap1 and 2 which are still on 1.1.4). Could that be causing the checksum to fail?

I'm pretty new to ldap too. Should I be using ldapmodify as part of the docker build process (custom image)? It looked like that setting didn't replicate to ldap2 from what I could see. I'm guessing this is a local config that isn't replicated.

**Comment by osixia** [comment]
The tls certificate probleme that first stop the container seems to be solved,
unfortunatly this can't fix the checksum problem created by the previous container version, you need to do it manualy.

maybe this can help: 
https://injustfiveminutes.com/2014/10/28/how-to-fix-ldif_read_file-checksum-error/

try to caculate the checksum and manualy update it in the file:
`CRC32 a2f6acd0`

**Comment by adamlc** [comment]
Thanks @osixia. Since this is a slave server could I simply delete the volumes and start again so everything gets replicated over?

**Comment by osixia** [comment]
Yes, but just in case don't delete the volumes but creates new ones :D

**Comment by adamlc** [comment]
That worked a treat, thanks 👯

**Comment by adamlc** [comment]
@osixia my other servers are also doing this now. It looks like the ldapmodify commands that I've been using aren't persistent across restarts, which is probably whats causing these issues with the checksum. Is there anything I should be doing to stop this happening?

**Comment by osixia** [comment]
this is very dependent of your configuration i can't help you with that sorry, maybe consider asking help to the openldap's guys

**Comment by adamlc** [comment]
Thanks for your help anyway. This is a great image BTW, keep up the good work!

**Comment by osixia** [comment]
thanks :)

**Comment by kopax** [comment]
I am running into a similar issue and this link is not valid anymore: https://injustfiveminutes.com/2014/10/28/how-to-fix-ldif_read_file-checksum-error/

**Comment by kopax** [comment]
Hi, I am still facing a similar issue. I am upgrading from 1.1.9 to 1.2.2 using an  existing database.

I have:

    Files /container/service/slapd/assets/certs/cert.crt and /container/service/slapd/assets/certs/key.key exists, fix files permissions
    TLS: warning: ignoring dhfile
     	additional info: modify/delete: olcSyncrepl: no such attribute
     ldap_delete: Server is unwilling to perform (53)
     ldap_modify: No such attribute (16)
    	additional info: modify/delete: olcSyncrepl: no such attribute
     ldap_delete: Server is unwilling to perform (53)
     ldap_modify: No such attribute (16)
     	additional info: modify/delete: olcServerID: no such attribute
