### ISSUE TITLE
Multi master replication sync failed on cn=config

### ISSUE THREAD

**Issue by snipking** [osixia/docker-openldap#78]
Hi

I have to docker-openldap running on different host with following configuration:   

```
docker run --name openldap -d -it -p 389:389 --restart unless-stopped --hostname dh03c01.xxxxx.local -e LDAP_ADMIN_PASSWORD="xxxxxx" -e LDAP_CONFIG_PASSWORD="xxxxxx" -e LDAP_DOMAIN="xxxxxx.com" -e LDAP_ORGANISATION="xxxxxx" -e LDAP_TLS=false -e LDAP_REPLICATION=true -e LDAP_REPLICATION_HOSTS="#PYTHON2BASH:['ldap://dh03c01.xxxxxx.local','ldap://dh04c01.xxxxxx.local']" -e LDAP_REPLICATION_CONFIG_SYNCPROV='binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1' -e LDAP_REPLICATION_DB_SYNCPROV='binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1' osixia/openldap --loglevel debug
```

The problem is cn=config not sync between two nodes.   

Node 1 error log   

```
57c8e393 null_callback : error code 0x35
57c8e393 syncrepl_entry: rid=002 be_add cn={5}mail,cn=schema,cn=config failed (53)
57c8e393 do_syncrepl: rid=002 rc 53 retrying
```
   
Node 2 error log

```
57c8e3c4 null_callback : error code 0x35
57c8e3c4 syncrepl_entry: rid=001 be_add cn={5}zarafa,cn=schema,cn=config failed (53)
57c8e3c4 do_syncrepl: rid=001 rc 53 retrying

```

Then when I list `/etc/ldap/slapd.d/cn=config/cn=schema/` always have following result:   

Node 1   

```
root@dh03c01:/# ls /etc/ldap/slapd.d/cn\=config/cn\=schema
cn={0}core.ldif    cn={11}mmc.ldif	cn={13}dhcp.ldif   cn={2}nis.ldif	     cn={4}ppolicy.ldif  cn={6}mail.ldif    cn={8}quota.ldif
cn={10}samba.ldif  cn={12}dnszone.ldif	cn={1}cosine.ldif  cn={3}inetorgperson.ldif  cn={5}zarafa.ldif	 cn={7}radius.ldif  cn={9}openssh-lpk.ldif
```

Node 2   

```
root@dh04c01:/# ls /etc/ldap/slapd.d/cn\=config/cn\=schema
cn={0}core.ldif		 cn={11}dhcp.ldif    cn={13}samba.ldif	cn={2}nis.ldif		  cn={4}ppolicy.ldif  cn={6}quota.ldif	 cn={8}mmc.ldif
cn={10}openssh-lpk.ldif  cn={12}radius.ldif  cn={1}cosine.ldif	cn={3}inetorgperson.ldif  cn={5}mail.ldif     cn={7}zarafa.ldif  cn={9}dnszone.ldif
```

I think the problem is openldap initialize configuration with different sequence. When I rerun the container, got exactly same error and same sequence. But when I run container on same docker host, it's working.

Any Ideas?

**Comment by snipking** [comment]
After remove some schema on node2 and restart node2, it's working fin.   

```
# rm cn\=\{5\}mail.ldif cn\=\{6\}quota.ldif cn\=\{7\}zarafa.ldif cn\=\{8\}mmc.ldif cn\=\{9\}dnszone.ldif cn\=\{10\}openssh-lpk.ldif cn\=\{11\}dhcp.ldif cn\=\{12\}radius.ldif cn\=\{13\}samba.ldif
```

**Comment by tiredofit** [comment]
I'm having the same issues, always cn={5} and it's either dhcp or radius which is the problem. I have received not so pleasant results from stopping and deleting like you.

**Comment by snipking** [comment]
@tiredofit 

Just delete schema after cn={5} on one of your node and restart the deleted node. The schema will sync from the other node with right order.

**Comment by andybrown668** [comment]
I've just seen this too and don't like the manual delete workaround - do I have another way to do this?

**Comment by apollo13** [comment]
I think this can be fixed by modifying https://github.com/osixia/docker-openldap/blob/hotfix-1.1.11/image/service/slapd/startup.sh#L217 to include a `|sort` in the find to process in a stable order? Then again I am surprised that the order is not stable. I will try to rebuild and report back.

**Comment by apollo13** [comment]
My fix seems to work :) Our containers are fine now and the order stays constant.

**Comment by andybrown668** [comment]
great!

**Comment by BertrandGouny** [comment]
@apollo13 can you make a pull request with your fix ? Thanks :)
