### ISSUE TITLE
Any chance this will be added back to dockerhub?

### ISSUE THREAD

**Issue by JonasT** [osixia/docker-openldap#79]
Is there any chance this will be added back to dockerhub? On dockerhub there is just a very cryptic line that it doesn't autobuild, but the Makefile even has a ```release``` target so that seems a bit unusual.
If there is a good technical reason why this can't be on dockerhub with an up-to-date pre-built image, then some sort of better explanation would be nice!

(I'm referring to https://hub.docker.com/r/osixia/openldap/ )

**Comment by JonasT** [comment]
Also it seems the image WAS actually updated quite recently. Maybe the very confusing text "Sorry this image is not an automated build, 2 years ago this feature was pretty shitty...
and it seems not possible to switch to automated build now."  should simply be removed?? Since it seems to be a normal, regularly updated image. However, that text makes it very confusing regarding whether this is actually still actively updated and maintained or not..

**Comment by osixia** [comment]
Hello,
Thank for your feedback, I just remove the confusing description. Indeed the image is periodically, updated and available on the hub, can I close this issue?

**Comment by JonasT** [comment]
Sure! Thanks for updating the text :smile:
