### ISSUE TITLE
Don't disable network access from outside

### ISSUE THREAD

**Issue by cknitt** [osixia/docker-openldap#8]
Currently, the install.sh script disables network access from outside:

```
# Enable access only from docker default network and localhost
echo "slapd: 172.17.0.0/255.255.0.0 127.0.0.1 : ALLOW" >> /etc/hosts.allow
echo "slapd: ALL : DENY" >> /etc/hosts.allow
```

However, it should be up to the user if he wants to make the LDAP port publicly accessible (by executing "docker run" with "-p" or "-P") or just internally (by using container linking).

Therefore, I would suggest removing this script, or at least running it optionally on container start and not hardcoded on container build.

**Comment by ofreax** [comment]
Done in af4e9f513a50c6801f1a0ab304bdb8856a2d1531 close in next release.

**Comment by cknitt** [comment]
Great! Thanks for the quick merge! :-)
