### ISSUE TITLE
Can't startup if container/service/slapd/assets/certs is host mounted directory

### ISSUE THREAD

**Issue by taggartgorman** [osixia/docker-openldap#80]
When I try to run the container with the following command:

`docker run --name ldap-service --hostname ldap-service --volume ~/openldapdocker/slapd/database:/var/lib/ldap --volume ~/openldapdocker/slapd/config:/etc/ldap/slapd.d --volume ~/openldapdocker/certs:/container/service/slapd/assets/certs --env LDAP_ORGANISATION="Example" --env LDAP_DOMAIN="local" --env LDAP_ADMIN_PASSWORD="password" osixia/openldap:1.1.6`

slapd fails with this output

> *** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

> To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
unable to load DH parameters
139999151150736:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:696:Expecting: DH PARAMETERS
*** /container/run/startup/slapd failed with status 1

> *** Killing all processes...

I am running docker 1.12.1 on Mac OS 10.10.5 (yes, I need to upgrade the OS).

Thanks

**Comment by osixia** [comment]
Hello,
I just copy past this on ubuntu and it worked,
is anyone with Mac OS can help ? :)

**Comment by taggartgorman** [comment]
Even after updating to macOS 10.12, I still have the issue. The image works for me as long as I don't try to mount the /container/service/slapd/assets/certs directory. Is there some way I can get to the generated cert without mounting this directory?

**Comment by taggartgorman** [comment]
Okay, I just discover the solution. I wiped out the contents of the mounted LDAP config and database directories and I was able to successfully start the OpenLDAP service. I guess some previous setting was causing trouble. Thanks for looking into this!

**Comment by adambom** [comment]
This is not fixed. See #83. Wiping the LDAP database every time you reboot is not a solution to this problem. As mentioned in #83 using `--copy-service` does not appear to fix the issue.

**Comment by robbyoconnor** [comment]
I am having this issue on Ubuntu 16.04.
