### ISSUE TITLE
old tag docker pull

### ISSUE THREAD

**Issue by Nexucis** [osixia/docker-openldap#81]
Hi,

I'm currently used the docker image osixia/openldap:v1.1.2. Some dude who depend of my project, tell me that they can't pull this image. 

I tryed to pull the image 1.1.2, and effectively I can't do it anymore :

```bash
$> docker pull osixia/openldap:1.1.2
Pulling repository docker.io/osixia/openldap
Tag 1.1.2 not found in repository docker.io/osixia/openldap

$> docker pull osixia/openldap:v1.1.2
Pulling repository docker.io/osixia/openldap
Tag v1.1.2 not found in repository docker.io/osixia/openldap
```

Did you remove some old tag from the docker hub ? 

Thanks for your help.

**Comment by osixia** [comment]
Hi,
all tags before 1.1.6 will be removed, these images are not concidered stable. Please concider using 1.1.6+. Thanks

**Comment by Nexucis** [comment]
thanks for replying. I'm good with that :). May be you should advertise others with this decision. What do you think ?

**Comment by osixia** [comment]
Done :)
thanks for your feedback
