### ISSUE TITLE
Cannot change bdb config

### ISSUE THREAD

**Issue by snipking** [osixia/docker-openldap#89]
Hi

I use following LDIF to enable the `DB_LOG_AUTOREMOVE` on BDB.

```
dn: olcDatabase={1}hdb,cn=config
changetype: modify
add: olcDbConfig
olcDbConfig: set_flags DB_LOG_AUTOREMOVE
```

And execute follow command in the container.

```
ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /add_log_autoremove.ldif 
```

But return this error: 

```
modifying entry "olcDatabase={1}hdb,cn=config"
ldap_modify: Inappropriate matching (18)
	additional info: modify/add: olcDbConfig: no equality matching rule
```

After do some search I try to use `replace` in LDIF as following: 

```
dn: olcDatabase={1}hdb,cn=config
changetype: modify
replace: olcDbConfig
olcDbConfig: set_cachesize 0 2097152 0
olcDbConfig: set_lk_max_objects 1500
olcDbConfig: set_lk_max_locks 1500
olcDbConfig: set_lk_max_lockers 1500
olcDbConfig: set_flags DB_LOG_AUTOREMOVE
```

Which just add `set_flags DB_LOG_AUTOREMOVE` after exist config.

But after execute `ldapmodify` the slapd killed.

```
modifying entry "olcDatabase={1}hdb,cn=config"
ldap_modify: Other (e.g., implementation specific) error (80)
	additional info: failed to reopen database, rc=22
```

Even if I use the `olcDbConfig` totally equal to the existing value, the slapd killed when I use `ldap_modify`.

How can I add `DB_LOG_AUTOREMOVE` to the BDB ?

**Comment by fbuchmeier** [comment]
Hi,

I'm encountering the same problem on Ubuntu 16.04 with slapd (Ubuntu) (May 11 2016 16:12:05). According to the logs this seems to be related to a Bug in the HDB/BDB backend.

```
11:50:44
5889d484 conn=1011 op=0 BIND dn="cn=config" method=128
11:50:44
5889d484 conn=1011 op=1 MOD attr=olcDbConfig
11:50:44
5889d484 conn=1011 op=1 MOD dn="olcDatabase={1}hdb,cn=config"
11:50:44
5889d484 hdb_cf_cleanup: failed to reopen database, rc=22
11:50:44
5889d484 bdb(dc=it-economics,dc=de): BDB4511 Error: closing the transaction region with active transactions
11:50:44
5889d484 bdb_db_close: database "dc=it-economics,dc=de": close failed: Invalid argument (22)
11:50:44
5889d484 conn=1011 op=1 RESULT tag=103 err=80 text=failed to reopen database, rc=22
11:50:44
5889d484 daemon: abnormal condition, shutdown initiated.
11:50:44
5889d484 conn=1011 fd=19 closed (slapd shutdown)
11:50:44
5889d484 conn=1009 fd=22 closed (slapd shutdown)
11:50:44
5889d484 slapd shutdown: waiting for 0 operations/tasks to finish
11:50:44
/entrypoint: line 63: 9 Segmentation fault (core dumped) /usr/sbin/slapd -h "ldapi:/// ldap://*:$LDAP_PORT/ ldaps://*:$LDAPS_PORT/" -g openldap -u openldap -F /etc/ldap/slapd.d -d$LOG_LEVEL
```

You can find more information here:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816294
* https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/DXiOTWQBVgg

The bottom line is:
> Anyway: at this point, upstream considers the BDB and HDB backends EOL, 
> provided for the convenience of existing users, but not really 
> maintained any more; migrating to the new LMDB backend is encouraged. 
> I'll see what I can do, but I have to warn you that I'm not optimistic 
> about actually getting this fixed. It looks non-trivial...

Hope this helps.

Flo.

**Comment by snipking** [comment]
@fbuchmeier 

Thanks for your information. I've seen these advise to change BDB to MDB and will do it sometimes.

For current BDB config error. I've found a walkthrough by put config in `/var/lib/ldap/DB_CONFIG`.
