### ISSUE TITLE
Can't restart container with replication active

### ISSUE THREAD

**Issue by dasmaeh** [osixia/docker-openldap#96]
I've successfully set up two containers on two different hosts on coreOS. After the first start replication working well between the two.
Restarting any of the containers fails: 
```
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/01-custom/my-env.yaml
/container/environment/99-default/default.yaml
/container/environment/99-default/default.startup.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Start OpenLDAP...
*** /container/run/startup/slapd failed with status 1

*** Killing all processes...
```
I've also started the container with `--loglevel debug`. I believe the following lines are essential:
```
Start OpenLDAP...
Waiting for OpenLDAP to start...
5845a3d0 @(#) $OpenLDAP: slapd  (Jan 16 2016 23:00:08) $
	root@chimera:/tmp/buildd/openldap-2.4.40+dfsg/debian/build/servers/slapd
5845a3d0 read_config: no serverID / URL match found. Check slapd -h arguments.
5845a3d0 slapd stopped.
5845a3d0 connections_destroy: nothing to destroy.
```
Replication config:
```
LDAP_REPLICATION: true
LDAP_REPLICATION_HOSTS: ['ldaps://ldap1.cbjck.de:636', 'ldaps://ldap2.cbjck.de:636']
```
As both URL resolve to the hosts (and one is on a dynamic IP) I did not set up anything in /etc/hosts. However DNS resolution seems to be working as everything is fine on first start.

Any ideas on what's wrong?

**Comment by osixia** [comment]
Hello,
did you start the container with the hostname set ?
```
docker run --hostname  ldap1.cbjck.de [your options] osixia/openldap:1.1.7
```

**Comment by dasmaeh** [comment]
Sure I did.

From manually setting up ldap replication I'm used to set a `olcServerID`. I can't find anything like this in `cn=config` however.

**Comment by dasmaeh** [comment]
The solution I found after reading the openldap docs and a lot of trial and error: don't use ldaps in `LDAP_REPLICATION_HOSTS`. While using it in `olcSyncRepls` is fine it's not working in `olcServerID`. That's also the reason I've done it differently before.
Using ldap only in `LDAP_REPLICATION_HOSTS` ( and starttls in `LDAP_REPLICATION_DB_SYNCPROV`) is working fine.
After all this seems to be a problem or lack of documentation in openldap.

**Comment by osixia** [comment]
thanks for the solution :)
