### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by scornea** [osixia/docker-openldap#99]
Hello and thank you for creating such container!

I am trying to deploy this container on Rancher using the docker-compose file that you supply (ofc adjusting the hostname and company) however, it doesn't want to start and all I get is this:

12/12/2016 18:17:41*** CONTAINER_LOG_LEVEL = 3 (info)
12/12/2016 18:17:41*** Search service in CONTAINER_SERVICE_DIR = /container/service :
12/12/2016 18:17:41*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
12/12/2016 18:17:41*** failed to link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools: [Errno 17] File exists
12/12/2016 18:17:41*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
12/12/2016 18:17:41*** failed to link /container/service/slapd/startup.sh to /container/run/startup/slapd: [Errno 17] File exists
12/12/2016 18:17:41*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
12/12/2016 18:17:41*** directory /container/run/process/slapd already exists
12/12/2016 18:17:41*** failed to link /container/service/slapd/process.sh to /container/run/process/slapd/run : [Errno 17] File exists
12/12/2016 18:17:41*** Set environment for startup files
12/12/2016 18:17:41*** Environment files will be proccessed in this order : 
12/12/2016 18:17:41Caution: previously defined variables will not be overriden.
12/12/2016 18:17:41/container/environment/99-default/default.yaml
12/12/2016 18:17:41/container/environment/99-default/default.startup.yaml
12/12/2016 18:17:41
12/12/2016 18:17:41To see how this files are processed and environment variables values,
12/12/2016 18:17:41run this container with '--loglevel debug'
12/12/2016 18:17:41*** Running /container/run/startup/:ssl-tools...
12/12/2016 18:17:41*** Running /container/run/startup/slapd...
12/12/2016 18:17:41Start OpenLDAP...
12/12/2016 18:17:42*** /container/run/startup/slapd failed with status 1
12/12/2016 18:17:42
12/12/2016 18:17:42*** Killing all processes...

Could you please tell me what I am doing wrong?

Thanks

**Comment by osixia** [comment]
duplicate #98
